#ifndef	__HANL_EORROR_H__
#define	__HANL_EORROR_H__
#define	HANL_PREDIC_OPEN_FAIL 1000
#define	HANL_ALIASDIC_OPEN_FAIL 1001
#define	HANL_USERDIC_OPEN_FAIL 1002
#define	HANL_STOPWORDDIC_OPEN_FAIL 1003
#define	HANL_SYSTEMDIC_OPEN_FAIL 1004
#define	HANL_FREQNOUNDIC_OPEN_FAIL 1005
#define	HANL_OVERFLOW_STACK_SIZE 2000
#define	HANL_OVERFLOW_RESULT_STRUCT 3000
#define	HANL_EOJUL_TOO_LONG 3001
#define	HANL_OVERFLOW_TAG_LIST 3002
#define	HANL_STACK_POINTER_SMALL_THAN_ZERO 3003
#define	HANL_INVALID_DATA 3005
#define	HANL_DEFAULT	10000


#endif
