#ifndef	__MORAN_TAGDEF_H__
#define	__MORAN_TAGDEF_H__
// This Header is generated at Tue Jun 27 12:43:00 2006


/* *************************************************************  
             MorAn Ver 4.0의 테그 정의 헤더 

                                  By Kim, Eung Gyun 
                                  jchern@daumcorp.com 

   본 헤더는 태그의 정의을 보관하는 헤더입니다.
   mkTagDef에 의해 자동으로 생성되었습니다.

   This Header is generated by mkTagDef at Tue Jun 27 12:43:00 2006
**************************************************************** */


#define 	LEFT_TAG_CNT  	103
#define 	RIGHT_TAG_CNT 	225

/* 좌측 태그의 Definition과 대응 번호 */
#define 	L_NUM_ST             0 	/*(  0) num_st          */
#define 	L_NUM_ED             1 	/*(  1) num_ed          */
#define 	L_NUM                2 	/*(  2) num             */
#define 	L_CONNUM             3 	/*(  3) connum          */
#define 	L_SIGNNUM            4 	/*(  4) signnum         */
#define 	L_ALPABET            5 	/*(  5) alpabet         */
#define 	L_CONALPABET         6 	/*(  6) conalpabet      */
#define 	L_ASCII              7 	/*(  7) ascii           */
#define 	L_HANUM              8 	/*(  8) hanum           */
#define 	L_NCP                9 	/*(  9) ncp             */
#define 	L_NCN                10 	/*( 10) ncn             */
#define 	L_NQ_JUSO            11 	/*( 11) nq_juso         */
#define 	L_NQ_PER             12 	/*( 12) nq_per          */
#define 	L_NQ_PER_HIS         13 	/*( 13) nq_per_his      */
#define 	L_NQ_PER_NOC         14 	/*( 14) nq_per_noc      */
#define 	L_NQ_FORPER          15 	/*( 15) nq_forper       */
#define 	L_NQ_LOC             16 	/*( 16) nq_loc          */
#define 	L_NQ_FORLOC          17 	/*( 17) nq_forloc       */
#define 	L_NQ_HISLOC          18 	/*( 18) nq_hisloc       */
#define 	L_NQ_COM             19 	/*( 19) nq_com          */
#define 	L_NQ_ETC             20 	/*( 20) nq_etc          */
#define 	L_NQ_ETC_NOC         21 	/*( 21) nq_etc_noc      */
#define 	L_NCN_F              22 	/*( 22) ncn_f           */
#define 	L_NCP_F              23 	/*( 23) ncp_f           */
#define 	L_NCN_NOCOM          24 	/*( 24) ncn_nocom       */
#define 	L_NCP_NOCOM          25 	/*( 25) ncp_nocom       */
#define 	L_PV                 26 	/*( 26) pv              */
#define 	L_PA                 27 	/*( 27) pa              */
#define 	L_NQ_PER1            28 	/*( 28) nq_per1         */
#define 	L_NQ_PER2            29 	/*( 29) nq_per2         */
#define 	L_NBU                30 	/*( 30) nbu             */
#define 	L_NBU_ONE            31 	/*( 31) nbu_one         */
#define 	L_NBU_E              32 	/*( 32) nbu_e           */
#define 	L_NBN_P              33 	/*( 33) nbn_p           */
#define 	L_NBN_N              34 	/*( 34) nbn_n           */
#define 	L_NC_ONE_IDX         35 	/*( 35) nc_one_idx      */
#define 	L_PV_AUX             36 	/*( 36) pv_aux          */
#define 	L_PA_AUX             37 	/*( 37) pa_aux          */
#define 	L_XSPV               38 	/*( 38) xspv            */
#define 	L_XSPA               39 	/*( 39) xspa            */
#define 	L_XS_NBU             40 	/*( 40) xs_nbu          */
#define 	L_PA_ISS             41 	/*( 41) pa_iss          */
#define 	L_CON                42 	/*( 42) con             */
#define 	L_XSP                43 	/*( 43) xsp             */
#define 	L_XSN_NCP            44 	/*( 44) xsn_ncp         */
#define 	L_XSN_NQ_PER_IDX     45 	/*( 45) xsn_nq_per_idx  */
#define 	L_XSN_NQ_PER_NOIDX   46 	/*( 46) xsn_nq_per_noidx */
#define 	L_XSN_NQ_PER2_NOIDX  47 	/*( 47) xsn_nq_per2_noidx */
#define 	L_XSN_NQ_WRK_IDX     48 	/*( 48) xsn_nq_wrk_idx  */
#define 	L_XSN_NQ_WRK_NOIDX   49 	/*( 49) xsn_nq_wrk_noidx */
#define 	L_XSN_NQ_LOC_IDX     50 	/*( 50) xsn_nq_loc_idx  */
#define 	L_XSN_NQ_LOC_NOIDX   51 	/*( 51) xsn_nq_loc_noidx */
#define 	L_XSN_NQ_ETC_ID      52 	/*( 52) xsn_nq_etc_idx  */
#define 	L_XSN_NQ_ETC_NOIDX   53 	/*( 53) xsn_nq_etc_noidx */
#define 	L_XSN_NQ_COM_ID      54 	/*( 54) xsn_nq_com_idx  */
#define 	L_XSN_NQ_COM_NOIDX   55 	/*( 55) xsn_nq_com_noidx */
#define 	L_XSN_NC_IDX         56 	/*( 56) xsn_nc_idx      */
#define 	L_XSN_NC_IDX2        57 	/*( 57) xsn_nc_idx2     */
#define 	L_XSN_NC_NOIDX       58 	/*( 58) xsn_nc_noidx    */
#define 	L_NP                 59 	/*( 59) np              */
#define 	L_NP_NOJUB           60 	/*( 60) np_nojub        */
#define 	L_NNO                61 	/*( 61) nno             */
#define 	L_NNC                62 	/*( 62) nnc             */
#define 	L_MMN                63 	/*( 63) mmn             */
#define 	L_MMA                64 	/*( 64) mma             */
#define 	L_MMD                65 	/*( 65) mmd             */
#define 	L_MA                 66 	/*( 66) ma              */
#define 	L_J_N                67 	/*( 67) j_n             */
#define 	L_J_YL               68 	/*( 68) j_yl            */
#define 	L_J_NL               69 	/*( 69) j_nl            */
#define 	L_J_Y                70 	/*( 70) j_y             */
#define 	L_J_C                71 	/*( 71) j_c             */
#define 	L_PER_C              72 	/*( 72) j_per           */
#define 	L_JP_Y               73 	/*( 73) jp_y            */
#define 	L_J_AUTO_N           74 	/*( 74) j_auto_n        */
#define 	L_J_AUTO_YL          75 	/*( 75) j_auto_yl       */
#define 	L_J_AUTO_C           76 	/*( 76) j_auto_c        */
#define 	L_JP_N               77 	/*( 77) jp_n            */
#define 	L_J_SPE_N            78 	/*( 78) j_spe_n         */
#define 	L_J_SPE_YL           79 	/*( 79) j_spe_yl        */
#define 	L_J_SPE_NL           80 	/*( 80) j_spe_nl        */
#define 	L_J_SPE_Y            81 	/*( 81) j_spe_y         */
#define 	L_J_SPE_C            82 	/*( 82) j_spe_c         */
#define 	L_J_SPE_JP           83 	/*( 83) j_spe_jp        */
#define 	L_J_SPE_IDX          84 	/*( 84) j_spe_idx       */
#define 	L_J_SUB_Y            85 	/*( 85) j_sub_y         */
#define 	L_J_SUB_N            86 	/*( 86) j_sub_n         */
#define 	L_J_SUB_L            87 	/*( 87) j_sub_l         */
#define 	L_NC_ONE_NOIDX       88 	/*( 88) nc_one_noidx    */
#define 	L_XSNP               89 	/*( 89) xsnp            */
#define 	L_EF                 90 	/*( 90) ef              */
#define 	L_EP                 91 	/*( 91) ep              */
#define 	L_ETN                92 	/*( 92) etn             */
#define 	L_XP                 93 	/*( 93) xp              */
#define 	L_I                  94 	/*( 94) i               */
#define 	L_BOE                95 	/*( 95) boe             */
#define 	L_EOE                96 	/*( 96) eoe             */
#define 	L_UNKNOWN            97 	/*( 97) unknown         */
#define 	L_UNOUN              98 	/*( 98) unoun           */
#define 	L_ENG                99 	/*( 99) eng             */
#define 	L_NUMB               100 	/*(100) numb            */
#define 	L_HANJA              101 	/*(101) hanja           */
#define 	L_MARK               102 	/*(102) mark            */

/* 우측 태그의 Definition과 대응 번호 */
#define 	R_HANUM_N            0 	/*(  0) hanum_n         */
#define 	R_HANUM_Y            1 	/*(  1) hanum_y         */
#define 	R_HANUM_L            2 	/*(  2) hanum_l         */
#define 	R_HANUM_X            3 	/*(  3) hanum_x         */
#define 	R_NUM_ST             4 	/*(  4) num_st          */
#define 	R_NUM_ED             5 	/*(  5) num_ed          */
#define 	R_NUM                6 	/*(  6) num             */
#define 	R_ASCII              7 	/*(  7) ascii           */
#define 	R_ALPABET            8 	/*(  8) alpabet         */
#define 	R_CONALPABET         9 	/*(  9) conalpabet      */
#define 	R_CONNUM             10 	/*( 10) connum          */
#define 	R_SIGNNUM            11 	/*( 11) signnum         */
#define 	R_NUM_N              12 	/*( 12) num_n           */
#define 	R_NUM_Y              13 	/*( 13) num_y           */
#define 	R_NUM_L              14 	/*( 14) num_l           */
#define 	R_NUM_X              15 	/*( 15) num_x           */
#define 	R_NQ_PER1            16 	/*( 16) nq_per1         */
#define 	R_NQ_JUSO_N          17 	/*( 17) nq_juso_n       */
#define 	R_NQ_JUSO_Y          18 	/*( 18) nq_juso_y       */
#define 	R_NQ_JUSO_L          19 	/*( 19) nq_juso_l       */
#define 	R_NQ_PER_N           20 	/*( 20) nq_per_n        */
#define 	R_NQ_PER_Y           21 	/*( 21) nq_per_y        */
#define 	R_NQ_PER_L           22 	/*( 22) nq_per_l        */
#define 	R_NQ_PER_HIS_N       23 	/*( 23) nq_per_his_n    */
#define 	R_NQ_PER_HIS_Y       24 	/*( 24) nq_per_his_y    */
#define 	R_NQ_PER_HIS_L       25 	/*( 25) nq_per_his_l    */
#define 	R_NQ_PER_NOC_N       26 	/*( 26) nq_per_noc_n    */
#define 	R_NQ_PER_NOC_Y       27 	/*( 27) nq_per_noc_y    */
#define 	R_NQ_PER_NOC_L       28 	/*( 28) nq_per_noc_l    */
#define 	R_NQ_FORPER_N        29 	/*( 29) nq_forper_n     */
#define 	R_NQ_FORPER_Y        30 	/*( 30) nq_forper_y     */
#define 	R_NQ_FORPER_L        31 	/*( 31) nq_forper_l     */
#define 	R_NQ_PER2_N          32 	/*( 32) nq_per2_n       */
#define 	R_NQ_PER2_Y          33 	/*( 33) nq_per2_y       */
#define 	R_NQ_PER2_L          34 	/*( 34) nq_per2_l       */
#define 	R_NQ_LOC_N           35 	/*( 35) nq_loc_n        */
#define 	R_NQ_LOC_Y           36 	/*( 36) nq_loc_y        */
#define 	R_NQ_LOC_L           37 	/*( 37) nq_loc_l        */
#define 	R_NQ_FORLOC_N        38 	/*( 38) nq_forloc_n     */
#define 	R_NQ_FORLOC_Y        39 	/*( 39) nq_forloc_y     */
#define 	R_NQ_FORLOC_L        40 	/*( 40) nq_forloc_l     */
#define 	R_NQ_HISLOC_N        41 	/*( 41) nq_hisloc_n     */
#define 	R_NQ_HISLOC_Y        42 	/*( 42) nq_hisloc_y     */
#define 	R_NQ_HISLOC_L        43 	/*( 43) nq_hisloc_l     */
#define 	R_NQ_COM_N           44 	/*( 44) nq_com_n        */
#define 	R_NQ_COM_Y           45 	/*( 45) nq_com_y        */
#define 	R_NQ_COm_L           46 	/*( 46) nq_com_l        */
#define 	R_NQ_ETC_N           47 	/*( 47) nq_etc_n        */
#define 	R_NQ_ETC_Y           48 	/*( 48) nq_etc_y        */
#define 	R_NQ_ETC_L           49 	/*( 49) nq_etc_l        */
#define 	R_NQ_ETC_NOC_N       50 	/*( 50) nq_etc_noc_n    */
#define 	R_NQ_ETC_NOC_Y       51 	/*( 51) nq_etc_noc_y    */
#define 	R_NQ_ETC_NOC_L       52 	/*( 52) nq_etc_noc_l    */
#define 	R_NCP_Y              53 	/*( 53) ncp_y           */
#define 	R_NCP_L              54 	/*( 54) ncp_l           */
#define 	R_NCP_N              55 	/*( 55) ncp_n           */
#define 	R_NCP_F_Y            56 	/*( 56) ncp_f_y         */
#define 	R_NCP_F_L            57 	/*( 57) ncp_f_l         */
#define 	R_NCP_F_N            58 	/*( 58) ncp_f_n         */
#define 	R_NCP_NOCOM_N        59 	/*( 59) ncp_nocom_n     */
#define 	R_NCP_NOCOM_Y        60 	/*( 60) ncp_nocom_y     */
#define 	R_NCP_NOCOM_L        61 	/*( 61) ncp_nocom_l     */
#define 	R_NCN_N              62 	/*( 62) ncn_n           */
#define 	R_NCN_Y              63 	/*( 63) ncn_y           */
#define 	R_NCN_L              64 	/*( 64) ncn_l           */
#define 	R_NCN_F_N            65 	/*( 65) ncn_f_n         */
#define 	R_NCN_F_Y            66 	/*( 66) ncn_f_y         */
#define 	R_NCN_F_L            67 	/*( 67) ncn_f_l         */
#define 	R_NCN_NOCOM_N        68 	/*( 68) ncn_nocom_n     */
#define 	R_NCN_NOCOM_Y        69 	/*( 69) ncn_nocom_y     */
#define 	R_NCN_NOCOM_L        70 	/*( 70) ncn_nocom_l     */
#define 	R_NCP_NX             71 	/*( 71) ncp_nx          */
#define 	R_NCP_YX             72 	/*( 72) ncp_yx          */
#define 	R_NCP_LX             73 	/*( 73) ncp_lx          */
#define 	R_NCN_NX             74 	/*( 74) ncn_nx          */
#define 	R_NCN_YX             75 	/*( 75) ncn_yx          */
#define 	R_NCN_LX             76 	/*( 76) ncn_lx          */
#define 	R_NC_ONE_IDX_N       77 	/*( 77) nc_one_idx_n    */
#define 	R_NC_ONE_IDX_Y       78 	/*( 78) nc_one_idx_y    */
#define 	R_NC_ONE_IDX_L       79 	/*( 79) nc_one_idx_l    */
#define 	R_NBU_E              80 	/*( 80) nbu_e           */
#define 	R_NBU_N              81 	/*( 81) nbu_n           */
#define 	R_NBU_Y              82 	/*( 82) nbu_y           */
#define 	R_NBU_L              83 	/*( 83) nbu_l           */
#define 	R_NBU_ONE_N          84 	/*( 84) nbu_one_n       */
#define 	R_NBU_ONE_Y          85 	/*( 85) nbu_one_y       */
#define 	R_NBU_ONE_L          86 	/*( 86) nbu_one_l       */
#define 	R_NBN_P_N            87 	/*( 87) nbn_p_n         */
#define 	R_NBN_P_Y            88 	/*( 88) nbn_p_y         */
#define 	R_NBN_P_L            89 	/*( 89) nbn_p_l         */
#define 	R_NBN_N_N            90 	/*( 90) nbn_n_n         */
#define 	R_NBN_N_Y            91 	/*( 91) nbn_n_y         */
#define 	R_NBN_N_L            92 	/*( 92) nbn_n_l         */
#define 	R_CON                93 	/*( 93) con             */
#define 	R_XSP_RG             94 	/*( 94) xsp_rg          */
#define 	R_XSP_YEO            95 	/*( 95) xsp_yeo         */
#define 	R_XSP_B              96 	/*( 96) xsp_b           */
#define 	R_XSP_S              97 	/*( 97) xsp_s           */
#define 	R_XSP_CON_YEO        98 	/*( 98) xsp_con_yeo     */
#define 	R_XSP_CON_B          99 	/*( 99) xsp_con_b       */
#define 	R_XSP_CON_S          100 	/*(100) xsp_con_s       */
#define 	R_XSN_N              101 	/*(101) xsn_n           */
#define 	R_XSN_Y              102 	/*(102) xsn_y           */
#define 	R_XSN_L              103 	/*(103) xsn_l           */
#define 	R_XSN_NCP_S          104 	/*(104) xsn_ncp_spe_n   */
#define 	R_XSN_NCP_N          105 	/*(105) xsn_ncp_n       */
#define 	R_XSN_NCP_Y          106 	/*(106) xsn_ncp_y       */
#define 	R_XSN_NCP_L          107 	/*(107) xsn_ncp_l       */
#define 	R_NP_N               108 	/*(108) np_n            */
#define 	R_NP_Y               109 	/*(109) np_y            */
#define 	R_NP_L               110 	/*(110) np_l            */
#define 	R_NP_NOJUB_N         111 	/*(111) np_nojub_n      */
#define 	R_NP_NOJUB_Y         112 	/*(112) np_nojub_y      */
#define 	R_NP_NOJUB_L         113 	/*(113) np_nojub_l      */
#define 	R_NNO_N              114 	/*(114) nno_n           */
#define 	R_NNO_Y              115 	/*(115) nno_y           */
#define 	R_NNO_L              116 	/*(116) nno_l           */
#define 	R_NNC_N              117 	/*(117) nnc_n           */
#define 	R_NNC_Y              118 	/*(118) nnc_y           */
#define 	R_NNC_L              119 	/*(119) nnc_l           */
#define 	R_MMN                120 	/*(120) mmn             */
#define 	R_MM$                121 	/*(121) mma             */
#define 	R_MMD                122 	/*(122) mmd             */
#define 	R_MA_N               123 	/*(123) ma_n            */
#define 	R_MA_Y               124 	/*(124) ma_y            */
#define 	R_MA_L               125 	/*(125) ma_l            */
#define 	R_J                  126 	/*(126) j               */
#define 	R_JP                 127 	/*(127) jp              */
#define 	R_J_AUTO             128 	/*(128) j_auto          */
#define 	R_J_SPE              129 	/*(129) j_spe           */
#define 	R_J_SUB              130 	/*(130) j_sub           */
#define 	R_PV_RG              131 	/*(131) pv_rg           */
#define 	R_PV_YEO             132 	/*(132) pv_yeo          */
#define 	R_PV_GEO             133 	/*(133) pv_geo          */
#define 	R_PV_NEO             134 	/*(134) pv_neo          */
#define 	R_PV_EU              135 	/*(135) pv_eu           */
#define 	R_PV_REU             136 	/*(136) pv_reu          */
#define 	R_PV_WOO             137 	/*(137) pv_woo          */
#define 	R_PV_REO             138 	/*(138) pv_reo          */
#define 	R_PV_D               139 	/*(139) pv_d            */
#define 	R_PV_L               140 	/*(140) pv_l            */
#define 	R_PV_B               141 	/*(141) pv_b            */
#define 	R_PV_S               142 	/*(142) pv_s            */
#define 	R_PV_CON_YEO         143 	/*(143) pv_con_yeo      */
#define 	R_PV_CON_GEO         144 	/*(144) pv_con_geo      */
#define 	R_PV_CON_NEO         145 	/*(145) pv_con_neo      */
#define 	R_PV_CON_EU          146 	/*(146) pv_con_eu       */
#define 	R_PV_CON_REU         147 	/*(147) pv_con_reu      */
#define 	R_PV_CON_WOO         148 	/*(148) pv_con_woo      */
#define 	R_PV_CON_REO         149 	/*(149) pv_con_reo      */
#define 	R_PV_CON_D           150 	/*(150) pv_con_d        */
#define 	R_PV_CON_L           151 	/*(151) pv_con_l        */
#define 	R_PV_CON_B           152 	/*(152) pv_con_b        */
#define 	R_PV_CON_S           153 	/*(153) pv_con_s        */
#define 	R_PA_RG              154 	/*(154) pa_rg           */
#define 	R_PA_ISS             155 	/*(155) pa_iss          */
#define 	R_PA_YEO             156 	/*(156) pa_yeo          */
#define 	R_PA_EU              157 	/*(157) pa_eu           */
#define 	R_PA_REU             158 	/*(158) pa_reu          */
#define 	R_PA_REO             159 	/*(159) pa_reo          */
#define 	R_PA_L               160 	/*(160) pa_l            */
#define 	R_PA_B               161 	/*(161) pa_b            */
#define 	R_PA_S               162 	/*(162) pa_s            */
#define 	R_PA_H               163 	/*(163) pa_h            */
#define 	R_PA_CON_YEO         164 	/*(164) pa_con_yeo      */
#define 	R_PA_CON_EU          165 	/*(165) pa_con_eu       */
#define 	R_PA_CON_REU         166 	/*(166) pa_con_reu      */
#define 	R_PA_CON_REO         167 	/*(167) pa_con_reo      */
#define 	R_PA_CON_L           168 	/*(168) pa_con_l        */
#define 	R_PA_CON_B           169 	/*(169) pa_con_b        */
#define 	R_PA_CON_S           170 	/*(170) pa_con_s        */
#define 	R_PA_CON_H           171 	/*(171) pa_con_h        */
#define 	R_PV_AUX_RG          172 	/*(172) pv_aux_rg       */
#define 	R_PV_AUX_YEO         173 	/*(173) pv_aux_yeo      */
#define 	R_PV_AUX_GEO         174 	/*(174) pv_aux_geo      */
#define 	R_PV_AUX_NEO         175 	/*(175) pv_aux_neo      */
#define 	R_PV_AUX_EU          176 	/*(176) pv_aux_eu       */
#define 	R_PV_AUX_REU         177 	/*(177) pv_aux_reu      */
#define 	R_PV_AUX_L           178 	/*(178) pv_aux_l        */
#define 	R_PV_AUX_B           179 	/*(179) pv_aux_b        */
#define 	R_PV_AUX_CON_YEO     180 	/*(180) pv_aux_con_yeo  */
#define 	R_PV_AUX_CON_GEO     181 	/*(181) pv_aux_con_geo  */
#define 	R_PV_AUX_CON_NEO     182 	/*(182) pv_aux_con_neo  */
#define 	R_PV_AUX_CON_EU      183 	/*(183) pv_aux_con_eu   */
#define 	R_PV_AUX_CON_REU     184 	/*(184) pv_aux_con_reu  */
#define 	R_PV_AUX_CON_L       185 	/*(185) pv_aux_con_l    */
#define 	R_PV_AUX_CON_B       186 	/*(186) pv_aux_con_b    */
#define 	R_PA_AUX_RG          187 	/*(187) pa_aux_rg       */
#define 	R_PA_AUX_ISS         188 	/*(188) pa_aux_iss      */
#define 	R_PA_AUX_YEO         189 	/*(189) pa_aux_yeo      */
#define 	R_PA_AUX_B           190 	/*(190) pa_aux_b        */
#define 	R_PA_AUX_CON_YEO     191 	/*(191) pa_aux_con_yeo  */
#define 	R_PA_AUX_CON_B       192 	/*(192) pa_aux_con_b    */
#define 	R_NC_ONE_NOIDX_N     193 	/*(193) nc_one_noidx_n  */
#define 	R_NC_ONE_NOIDX_Y     194 	/*(194) nc_one_noidx_y  */
#define 	R_NC_ONE_NOIDX_L     195 	/*(195) nc_one_noidx_l  */
#define 	R_XSPV               196 	/*(196) xspv            */
#define 	R_XSPA               197 	/*(197) xspa            */
#define 	R_EP                 198 	/*(198) ep              */
#define 	R_EF                 199 	/*(199) ef              */
#define 	R_EF_END             200 	/*(200) ef_end          */
#define 	R_EF_CON             201 	/*(201) ef_con          */
#define 	R_EFA                202 	/*(202) efa             */
#define 	R_ETN                203 	/*(203) etn             */
#define 	R_SPACE              204 	/*(204) ef_space        */
#define 	R_XP_NQ_PER_IDX      205 	/*(205) xp_nq_per_idx   */
#define 	R_XP_NQ_PER_NOIDX    206 	/*(206) xp_nq_per_noidx */
#define 	R_XP_NQ_LOC_IDX      207 	/*(207) xp_nq_loc_idx   */
#define 	R_XP_NQ_LOC_NOIDX    208 	/*(208) xp_nq_loc_noidx */
#define 	R_XP_NQ_ETC_IDX      209 	/*(209) xp_nq_etc_idx   */
#define 	R_XP_NQ_ETC_NOIDX    210 	/*(210) xp_nq_etc_noidx */
#define 	R_XP_NC_ID           211 	/*(211) xp_nc_idx       */
#define 	R_XP_NC_NOIDX        212 	/*(212) xp_nc_noidx     */
#define 	R_I                  213 	/*(213) i               */
#define 	R_BOE                214 	/*(214) boe             */
#define 	R_EOE                215 	/*(215) eoe             */
#define 	R_UNKNOWN            216 	/*(216) unknown         */
#define 	R_UNOUN_N            217 	/*(217) unoun_n         */
#define 	R_UNOUN_Y            218 	/*(218) unoun_y         */
#define 	R_UNOUN_L            219 	/*(219) unoun_l         */
#define 	R_ENG_N              220 	/*(220) eng_n           */
#define 	R_ENG_Y              221 	/*(221) eng_y           */
#define 	R_ENG_C              222 	/*(222) eng_c           */
#define 	R_HANJA              223 	/*(223) hanja           */
#define 	R_MARK               224 	/*(224) mark            */


/* *************************************************************  
             MorAn Ver 4.0의 색인정보 헤더 

                                  By Kim, Eung Gyun 
                                  jchern@daumcorp.com 

   본 헤더는 색인어로 추출할때 TYPE을 정의합니다.
   mkTagDef에 의해 자동으로 생성되었습니다.

   This Header is generated by mkTagDef at Tue Jun 27 12:43:00 2006
**************************************************************** */


static char     L_Tag_Idx[LEFT_TAG_CNT] = {
/*(  0) num_st          */ 	1, 
/*(  1) num_ed          */ 	1, 
/*(  2) num             */ 	1, 
/*(  3) connum          */ 	2, 
/*(  4) signnum         */ 	2, 
/*(  5) alpabet         */ 	1, 
/*(  6) conalpabet      */ 	2, 
/*(  7) ascii           */ 	1, 
/*(  8) hanum           */ 	1, 
/*(  9) ncp             */ 	1, 
/*( 10) ncn             */ 	1, 
/*( 11) nq_juso         */ 	1, 
/*( 12) nq_per          */ 	1, 
/*( 13) nq_per_his      */ 	1, 
/*( 14) nq_per_noc      */ 	1, 
/*( 15) nq_forper       */ 	1, 
/*( 16) nq_loc          */ 	1, 
/*( 17) nq_forloc       */ 	1, 
/*( 18) nq_hisloc       */ 	1, 
/*( 19) nq_com          */ 	1, 
/*( 20) nq_etc          */ 	1, 
/*( 21) nq_etc_noc      */ 	1, 
/*( 22) ncn_f           */ 	1, 
/*( 23) ncp_f           */ 	1, 
/*( 24) ncn_nocom       */ 	1, 
/*( 25) ncp_nocom       */ 	1, 
/*( 26) pv              */ 	1, 
/*( 27) pa              */ 	1, 
/*( 28) nq_per1         */ 	1, 
/*( 29) nq_per2         */ 	1, 
/*( 30) nbu             */ 	1, 
/*( 31) nbu_one         */ 	1, 
/*( 32) nbu_e           */ 	1, 
/*( 33) nbn_p           */ 	1, 
/*( 34) nbn_n           */ 	1, 
/*( 35) nc_one_idx      */ 	1, 
/*( 36) pv_aux          */ 	3, 
/*( 37) pa_aux          */ 	3, 
/*( 38) xspv            */ 	3, 
/*( 39) xspa            */ 	3, 
/*( 40) xs_nbu          */ 	3, 
/*( 41) pa_iss          */ 	3, 
/*( 42) con             */ 	3, 
/*( 43) xsp             */ 	4, 
/*( 44) xsn_ncp         */ 	1, 
/*( 45) xsn_nq_per_idx  */ 	3, 
/*( 46) xsn_nq_per_noidx */ 	3, 
/*( 47) xsn_nq_per2_noidx */ 	0, 
/*( 48) xsn_nq_wrk_idx  */ 	3, 
/*( 49) xsn_nq_wrk_noidx */ 	3, 
/*( 50) xsn_nq_loc_idx  */ 	3, 
/*( 51) xsn_nq_loc_noidx */ 	3, 
/*( 52) xsn_nq_etc_idx  */ 	3, 
/*( 53) xsn_nq_etc_noidx */ 	3, 
/*( 54) xsn_nq_com_idx  */ 	3, 
/*( 55) xsn_nq_com_noidx */ 	3, 
/*( 56) xsn_nc_idx      */ 	3, 
/*( 57) xsn_nc_idx2     */ 	3, 
/*( 58) xsn_nc_noidx    */ 	3, 
/*( 59) np              */ 	1, 
/*( 60) np_nojub        */ 	1, 
/*( 61) nno             */ 	3, 
/*( 62) nnc             */ 	3, 
/*( 63) mmn             */ 	3, 
/*( 64) mma             */ 	3, 
/*( 65) mmd             */ 	3, 
/*( 66) ma              */ 	3, 
/*( 67) j_n             */ 	4, 
/*( 68) j_yl            */ 	4, 
/*( 69) j_nl            */ 	4, 
/*( 70) j_y             */ 	4, 
/*( 71) j_c             */ 	4, 
/*( 72) j_per           */ 	4, 
/*( 73) jp_y            */ 	4, 
/*( 74) j_auto_n        */ 	4, 
/*( 75) j_auto_yl       */ 	4, 
/*( 76) j_auto_c        */ 	4, 
/*( 77) jp_n            */ 	4, 
/*( 78) j_spe_n         */ 	4, 
/*( 79) j_spe_yl        */ 	4, 
/*( 80) j_spe_nl        */ 	4, 
/*( 81) j_spe_y         */ 	4, 
/*( 82) j_spe_c         */ 	4, 
/*( 83) j_spe_jp        */ 	4, 
/*( 84) j_spe_idx       */ 	1, 
/*( 85) j_sub_y         */ 	1, 
/*( 86) j_sub_n         */ 	1, 
/*( 87) j_sub_l         */ 	1, 
/*( 88) nc_one_noidx    */ 	1, 
/*( 89) xsnp            */ 	3, 
/*( 90) ef              */ 	4, 
/*( 91) ep              */ 	4, 
/*( 92) etn             */ 	4, 
/*( 93) xp              */ 	1, 
/*( 94) i               */ 	3, 
/*( 95) boe             */ 	0, 
/*( 96) eoe             */ 	0, 
/*( 97) unknown         */ 	3, 
/*( 98) unoun           */ 	3, 
/*( 99) eng             */ 	3, 
/*(100) numb            */ 	3, 
/*(101) hanja           */ 	3, 
/*(102) mark            */ 	3};



static char      R_Tag_Idx[RIGHT_TAG_CNT] = {
/*(  0) hanum_n         */ 	1, 
/*(  1) hanum_y         */ 	1, 
/*(  2) hanum_l         */ 	1, 
/*(  3) hanum_x         */ 	1, 
/*(  4) num_st          */ 	1, 
/*(  5) num_ed          */ 	1, 
/*(  6) num             */ 	1, 
/*(  7) ascii           */ 	1, 
/*(  8) alpabet         */ 	1, 
/*(  9) conalpabet      */ 	1, 
/*( 10) connum          */ 	1, 
/*( 11) signnum         */ 	1, 
/*( 12) num_n           */ 	1, 
/*( 13) num_y           */ 	1, 
/*( 14) num_l           */ 	1, 
/*( 15) num_x           */ 	1, 
/*( 16) nq_per1         */ 	1, 
/*( 17) nq_juso_n       */ 	1, 
/*( 18) nq_juso_y       */ 	1, 
/*( 19) nq_juso_l       */ 	1, 
/*( 20) nq_per_n        */ 	1, 
/*( 21) nq_per_y        */ 	1, 
/*( 22) nq_per_l        */ 	1, 
/*( 23) nq_per_his_n    */ 	1, 
/*( 24) nq_per_his_y    */ 	1, 
/*( 25) nq_per_his_l    */ 	1, 
/*( 26) nq_per_noc_n    */ 	1, 
/*( 27) nq_per_noc_y    */ 	1, 
/*( 28) nq_per_noc_l    */ 	1, 
/*( 29) nq_forper_n     */ 	1, 
/*( 30) nq_forper_y     */ 	1, 
/*( 31) nq_forper_l     */ 	1, 
/*( 32) nq_per2_n       */ 	1, 
/*( 33) nq_per2_y       */ 	1, 
/*( 34) nq_per2_l       */ 	1, 
/*( 35) nq_loc_n        */ 	1, 
/*( 36) nq_loc_y        */ 	1, 
/*( 37) nq_loc_l        */ 	1, 
/*( 38) nq_forloc_n     */ 	1, 
/*( 39) nq_forloc_y     */ 	1, 
/*( 40) nq_forloc_l     */ 	1, 
/*( 41) nq_hisloc_n     */ 	1, 
/*( 42) nq_hisloc_y     */ 	1, 
/*( 43) nq_hisloc_l     */ 	1, 
/*( 44) nq_com_n        */ 	1, 
/*( 45) nq_com_y        */ 	1, 
/*( 46) nq_com_l        */ 	1, 
/*( 47) nq_etc_n        */ 	1, 
/*( 48) nq_etc_y        */ 	1, 
/*( 49) nq_etc_l        */ 	1, 
/*( 50) nq_etc_noc_n    */ 	1, 
/*( 51) nq_etc_noc_y    */ 	1, 
/*( 52) nq_etc_noc_l    */ 	1, 
/*( 53) ncp_y           */ 	1, 
/*( 54) ncp_l           */ 	1, 
/*( 55) ncp_n           */ 	1, 
/*( 56) ncp_f_y         */ 	1, 
/*( 57) ncp_f_l         */ 	1, 
/*( 58) ncp_f_n         */ 	1, 
/*( 59) ncp_nocom_n     */ 	1, 
/*( 60) ncp_nocom_y     */ 	1, 
/*( 61) ncp_nocom_l     */ 	1, 
/*( 62) ncn_n           */ 	1, 
/*( 63) ncn_y           */ 	1, 
/*( 64) ncn_l           */ 	1, 
/*( 65) ncn_f_n         */ 	1, 
/*( 66) ncn_f_y         */ 	1, 
/*( 67) ncn_f_l         */ 	1, 
/*( 68) ncn_nocom_n     */ 	1, 
/*( 69) ncn_nocom_y     */ 	1, 
/*( 70) ncn_nocom_l     */ 	1, 
/*( 71) ncp_nx          */ 	1, 
/*( 72) ncp_yx          */ 	1, 
/*( 73) ncp_lx          */ 	1, 
/*( 74) ncn_nx          */ 	1, 
/*( 75) ncn_yx          */ 	1, 
/*( 76) ncn_lx          */ 	1, 
/*( 77) nc_one_idx_n    */ 	1, 
/*( 78) nc_one_idx_y    */ 	1, 
/*( 79) nc_one_idx_l    */ 	1, 
/*( 80) nbu_e           */ 	1, 
/*( 81) nbu_n           */ 	1, 
/*( 82) nbu_y           */ 	1, 
/*( 83) nbu_l           */ 	1, 
/*( 84) nbu_one_n       */ 	1, 
/*( 85) nbu_one_y       */ 	1, 
/*( 86) nbu_one_l       */ 	1, 
/*( 87) nbn_p_n         */ 	1, 
/*( 88) nbn_p_y         */ 	1, 
/*( 89) nbn_p_l         */ 	1, 
/*( 90) nbn_n_n         */ 	1, 
/*( 91) nbn_n_y         */ 	1, 
/*( 92) nbn_n_l         */ 	1, 
/*( 93) con             */ 	1, 
/*( 94) xsp_rg          */ 	1, 
/*( 95) xsp_yeo         */ 	1, 
/*( 96) xsp_b           */ 	1, 
/*( 97) xsp_s           */ 	1, 
/*( 98) xsp_con_yeo     */ 	1, 
/*( 99) xsp_con_b       */ 	1, 
/*(100) xsp_con_s       */ 	1, 
/*(101) xsn_n           */ 	1, 
/*(102) xsn_y           */ 	1, 
/*(103) xsn_l           */ 	1, 
/*(104) xsn_ncp_spe_n   */ 	1, 
/*(105) xsn_ncp_n       */ 	1, 
/*(106) xsn_ncp_y       */ 	1, 
/*(107) xsn_ncp_l       */ 	1, 
/*(108) np_n            */ 	1, 
/*(109) np_y            */ 	1, 
/*(110) np_l            */ 	1, 
/*(111) np_nojub_n      */ 	1, 
/*(112) np_nojub_y      */ 	1, 
/*(113) np_nojub_l      */ 	1, 
/*(114) nno_n           */ 	1, 
/*(115) nno_y           */ 	1, 
/*(116) nno_l           */ 	1, 
/*(117) nnc_n           */ 	1, 
/*(118) nnc_y           */ 	1, 
/*(119) nnc_l           */ 	1, 
/*(120) mmn             */ 	1, 
/*(121) mma             */ 	1, 
/*(122) mmd             */ 	1, 
/*(123) ma_n            */ 	1, 
/*(124) ma_y            */ 	1, 
/*(125) ma_l            */ 	1, 
/*(126) j               */ 	0, 
/*(127) jp              */ 	0, 
/*(128) j_auto          */ 	0, 
/*(129) j_spe           */ 	0, 
/*(130) j_sub           */ 	0, 
/*(131) pv_rg           */ 	1, 
/*(132) pv_yeo          */ 	1, 
/*(133) pv_geo          */ 	1, 
/*(134) pv_neo          */ 	1, 
/*(135) pv_eu           */ 	1, 
/*(136) pv_reu          */ 	1, 
/*(137) pv_woo          */ 	1, 
/*(138) pv_reo          */ 	1, 
/*(139) pv_d            */ 	1, 
/*(140) pv_l            */ 	1, 
/*(141) pv_b            */ 	1, 
/*(142) pv_s            */ 	1, 
/*(143) pv_con_yeo      */ 	1, 
/*(144) pv_con_geo      */ 	1, 
/*(145) pv_con_neo      */ 	1, 
/*(146) pv_con_eu       */ 	1, 
/*(147) pv_con_reu      */ 	1, 
/*(148) pv_con_woo      */ 	1, 
/*(149) pv_con_reo      */ 	1, 
/*(150) pv_con_d        */ 	1, 
/*(151) pv_con_l        */ 	1, 
/*(152) pv_con_b        */ 	1, 
/*(153) pv_con_s        */ 	1, 
/*(154) pa_rg           */ 	1, 
/*(155) pa_iss          */ 	1, 
/*(156) pa_yeo          */ 	1, 
/*(157) pa_eu           */ 	1, 
/*(158) pa_reu          */ 	1, 
/*(159) pa_reo          */ 	1, 
/*(160) pa_l            */ 	1, 
/*(161) pa_b            */ 	1, 
/*(162) pa_s            */ 	1, 
/*(163) pa_h            */ 	1, 
/*(164) pa_con_yeo      */ 	1, 
/*(165) pa_con_eu       */ 	1, 
/*(166) pa_con_reu      */ 	1, 
/*(167) pa_con_reo      */ 	1, 
/*(168) pa_con_l        */ 	1, 
/*(169) pa_con_b        */ 	1, 
/*(170) pa_con_s        */ 	1, 
/*(171) pa_con_h        */ 	1, 
/*(172) pv_aux_rg       */ 	1, 
/*(173) pv_aux_yeo      */ 	1, 
/*(174) pv_aux_geo      */ 	1, 
/*(175) pv_aux_neo      */ 	1, 
/*(176) pv_aux_eu       */ 	1, 
/*(177) pv_aux_reu      */ 	1, 
/*(178) pv_aux_l        */ 	1, 
/*(179) pv_aux_b        */ 	1, 
/*(180) pv_aux_con_yeo  */ 	1, 
/*(181) pv_aux_con_geo  */ 	1, 
/*(182) pv_aux_con_neo  */ 	1, 
/*(183) pv_aux_con_eu   */ 	1, 
/*(184) pv_aux_con_reu  */ 	1, 
/*(185) pv_aux_con_l    */ 	1, 
/*(186) pv_aux_con_b    */ 	1, 
/*(187) pa_aux_rg       */ 	1, 
/*(188) pa_aux_iss      */ 	1, 
/*(189) pa_aux_yeo      */ 	1, 
/*(190) pa_aux_b        */ 	1, 
/*(191) pa_aux_con_yeo  */ 	1, 
/*(192) pa_aux_con_b    */ 	1, 
/*(193) nc_one_noidx_n  */ 	1, 
/*(194) nc_one_noidx_y  */ 	1, 
/*(195) nc_one_noidx_l  */ 	1, 
/*(196) xspv            */ 	1, 
/*(197) xspa            */ 	1, 
/*(198) ep              */ 	1, 
/*(199) ef              */ 	2, 
/*(200) ef_end          */ 	2, 
/*(201) ef_con          */ 	2, 
/*(202) efa             */ 	2, 
/*(203) etn             */ 	2, 
/*(204) ef_space        */ 	2, 
/*(205) xp_nq_per_idx   */ 	1, 
/*(206) xp_nq_per_noidx */ 	1, 
/*(207) xp_nq_loc_idx   */ 	1, 
/*(208) xp_nq_loc_noidx */ 	1, 
/*(209) xp_nq_etc_idx   */ 	1, 
/*(210) xp_nq_etc_noidx */ 	1, 
/*(211) xp_nc_idx       */ 	1, 
/*(212) xp_nc_noidx     */ 	1, 
/*(213) i               */ 	1, 
/*(214) boe             */ 	0, 
/*(215) eoe             */ 	0, 
/*(216) unknown         */ 	1, 
/*(217) unoun_n         */ 	1, 
/*(218) unoun_y         */ 	1, 
/*(219) unoun_l         */ 	1, 
/*(220) eng_n           */ 	1, 
/*(221) eng_y           */ 	1, 
/*(222) eng_c           */ 	1, 
/*(223) hanja           */ 	1, 
/*(224) mark            */ 	1};


/* *************************************************************  
             MorAn Ver 4.0의 철자복원정보 헤더 

                                  By Kim, Eung Gyun 
                                  jchern@daumcorp.com 

   본 헤더는 변형된 철자를 복원하는 정보를 보관하는 헤더입니다.
   mkTagDef에 의해 자동으로 생성되었습니다.

   This Header is generated by mkTagDef at Tue Jun 27 12:43:00 2006
**************************************************************** */


static char    L_Tag_Action[LEFT_TAG_CNT] = {
/*(  0) num_st          */ 	0, 
/*(  1) num_ed          */ 	2, 
/*(  2) num             */ 	0, 
/*(  3) connum          */ 	2, 
/*(  4) signnum         */ 	2, 
/*(  5) alpabet         */ 	1, 
/*(  6) conalpabet      */ 	0, 
/*(  7) ascii           */ 	0, 
/*(  8) hanum           */ 	0, 
/*(  9) ncp             */ 	0, 
/*( 10) ncn             */ 	0, 
/*( 11) nq_juso         */ 	0, 
/*( 12) nq_per          */ 	0, 
/*( 13) nq_per_his      */ 	0, 
/*( 14) nq_per_noc      */ 	0, 
/*( 15) nq_forper       */ 	0, 
/*( 16) nq_loc          */ 	0, 
/*( 17) nq_forloc       */ 	0, 
/*( 18) nq_hisloc       */ 	0, 
/*( 19) nq_com          */ 	0, 
/*( 20) nq_etc          */ 	0, 
/*( 21) nq_etc_noc      */ 	0, 
/*( 22) ncn_f           */ 	0, 
/*( 23) ncp_f           */ 	0, 
/*( 24) ncn_nocom       */ 	0, 
/*( 25) ncp_nocom       */ 	0, 
/*( 26) pv              */ 	0, 
/*( 27) pa              */ 	0, 
/*( 28) nq_per1         */ 	0, 
/*( 29) nq_per2         */ 	1, 
/*( 30) nbu             */ 	0, 
/*( 31) nbu_one         */ 	0, 
/*( 32) nbu_e           */ 	0, 
/*( 33) nbn_p           */ 	0, 
/*( 34) nbn_n           */ 	0, 
/*( 35) nc_one_idx      */ 	0, 
/*( 36) pv_aux          */ 	0, 
/*( 37) pa_aux          */ 	0, 
/*( 38) xspv            */ 	0, 
/*( 39) xspa            */ 	0, 
/*( 40) xs_nbu          */ 	0, 
/*( 41) pa_iss          */ 	0, 
/*( 42) con             */ 	0, 
/*( 43) xsp             */ 	0, 
/*( 44) xsn_ncp         */ 	1, 
/*( 45) xsn_nq_per_idx  */ 	0, 
/*( 46) xsn_nq_per_noidx */ 	0, 
/*( 47) xsn_nq_per2_noidx */ 	0, 
/*( 48) xsn_nq_wrk_idx  */ 	0, 
/*( 49) xsn_nq_wrk_noidx */ 	0, 
/*( 50) xsn_nq_loc_idx  */ 	0, 
/*( 51) xsn_nq_loc_noidx */ 	0, 
/*( 52) xsn_nq_etc_idx  */ 	0, 
/*( 53) xsn_nq_etc_noidx */ 	0, 
/*( 54) xsn_nq_com_idx  */ 	0, 
/*( 55) xsn_nq_com_noidx */ 	0, 
/*( 56) xsn_nc_idx      */ 	0, 
/*( 57) xsn_nc_idx2     */ 	0, 
/*( 58) xsn_nc_noidx    */ 	0, 
/*( 59) np              */ 	0, 
/*( 60) np_nojub        */ 	0, 
/*( 61) nno             */ 	0, 
/*( 62) nnc             */ 	2, 
/*( 63) mmn             */ 	0, 
/*( 64) mma             */ 	0, 
/*( 65) mmd             */ 	0, 
/*( 66) ma              */ 	0, 
/*( 67) j_n             */ 	0, 
/*( 68) j_yl            */ 	0, 
/*( 69) j_nl            */ 	0, 
/*( 70) j_y             */ 	0, 
/*( 71) j_c             */ 	0, 
/*( 72) j_per           */ 	0, 
/*( 73) jp_y            */ 	0, 
/*( 74) j_auto_n        */ 	0, 
/*( 75) j_auto_yl       */ 	0, 
/*( 76) j_auto_c        */ 	0, 
/*( 77) jp_n            */ 	0, 
/*( 78) j_spe_n         */ 	0, 
/*( 79) j_spe_yl        */ 	0, 
/*( 80) j_spe_nl        */ 	0, 
/*( 81) j_spe_y         */ 	0, 
/*( 82) j_spe_c         */ 	0, 
/*( 83) j_spe_jp        */ 	0, 
/*( 84) j_spe_idx       */ 	0, 
/*( 85) j_sub_y         */ 	0, 
/*( 86) j_sub_n         */ 	0, 
/*( 87) j_sub_l         */ 	0, 
/*( 88) nc_one_noidx    */ 	0, 
/*( 89) xsnp            */ 	0, 
/*( 90) ef              */ 	0, 
/*( 91) ep              */ 	0, 
/*( 92) etn             */ 	0, 
/*( 93) xp              */ 	0, 
/*( 94) i               */ 	0, 
/*( 95) boe             */ 	0, 
/*( 96) eoe             */ 	0, 
/*( 97) unknown         */ 	0, 
/*( 98) unoun           */ 	0, 
/*( 99) eng             */ 	2, 
/*(100) numb            */ 	0, 
/*(101) hanja           */ 	0, 
/*(102) mark            */ 	0};



static char      R_Tag_Action[RIGHT_TAG_CNT] = {
/*(  0) hanum_n         */ 	0, 
/*(  1) hanum_y         */ 	0, 
/*(  2) hanum_l         */ 	0, 
/*(  3) hanum_x         */ 	0, 
/*(  4) num_st          */ 	3, 
/*(  5) num_ed          */ 	0, 
/*(  6) num             */ 	0, 
/*(  7) ascii           */ 	0, 
/*(  8) alpabet         */ 	0, 
/*(  9) conalpabet      */ 	2, 
/*( 10) connum          */ 	0, 
/*( 11) signnum         */ 	0, 
/*( 12) num_n           */ 	0, 
/*( 13) num_y           */ 	0, 
/*( 14) num_l           */ 	0, 
/*( 15) num_x           */ 	0, 
/*( 16) nq_per1         */ 	3, 
/*( 17) nq_juso_n       */ 	0, 
/*( 18) nq_juso_y       */ 	0, 
/*( 19) nq_juso_l       */ 	0, 
/*( 20) nq_per_n        */ 	0, 
/*( 21) nq_per_y        */ 	0, 
/*( 22) nq_per_l        */ 	0, 
/*( 23) nq_per_his_n    */ 	0, 
/*( 24) nq_per_his_y    */ 	0, 
/*( 25) nq_per_his_l    */ 	0, 
/*( 26) nq_per_noc_n    */ 	0, 
/*( 27) nq_per_noc_y    */ 	0, 
/*( 28) nq_per_noc_l    */ 	0, 
/*( 29) nq_forper_n     */ 	0, 
/*( 30) nq_forper_y     */ 	0, 
/*( 31) nq_forper_l     */ 	0, 
/*( 32) nq_per2_n       */ 	0, 
/*( 33) nq_per2_y       */ 	0, 
/*( 34) nq_per2_l       */ 	0, 
/*( 35) nq_loc_n        */ 	0, 
/*( 36) nq_loc_y        */ 	0, 
/*( 37) nq_loc_l        */ 	0, 
/*( 38) nq_forloc_n     */ 	0, 
/*( 39) nq_forloc_y     */ 	0, 
/*( 40) nq_forloc_l     */ 	0, 
/*( 41) nq_hisloc_n     */ 	0, 
/*( 42) nq_hisloc_y     */ 	0, 
/*( 43) nq_hisloc_l     */ 	0, 
/*( 44) nq_com_n        */ 	0, 
/*( 45) nq_com_y        */ 	0, 
/*( 46) nq_com_l        */ 	0, 
/*( 47) nq_etc_n        */ 	0, 
/*( 48) nq_etc_y        */ 	0, 
/*( 49) nq_etc_l        */ 	0, 
/*( 50) nq_etc_noc_n    */ 	0, 
/*( 51) nq_etc_noc_y    */ 	0, 
/*( 52) nq_etc_noc_l    */ 	0, 
/*( 53) ncp_y           */ 	0, 
/*( 54) ncp_l           */ 	0, 
/*( 55) ncp_n           */ 	0, 
/*( 56) ncp_f_y         */ 	0, 
/*( 57) ncp_f_l         */ 	0, 
/*( 58) ncp_f_n         */ 	0, 
/*( 59) ncp_nocom_n     */ 	0, 
/*( 60) ncp_nocom_y     */ 	0, 
/*( 61) ncp_nocom_l     */ 	0, 
/*( 62) ncn_n           */ 	0, 
/*( 63) ncn_y           */ 	0, 
/*( 64) ncn_l           */ 	0, 
/*( 65) ncn_f_n         */ 	0, 
/*( 66) ncn_f_y         */ 	0, 
/*( 67) ncn_f_l         */ 	0, 
/*( 68) ncn_nocom_n     */ 	0, 
/*( 69) ncn_nocom_y     */ 	0, 
/*( 70) ncn_nocom_l     */ 	0, 
/*( 71) ncp_nx          */ 	0, 
/*( 72) ncp_yx          */ 	0, 
/*( 73) ncp_lx          */ 	0, 
/*( 74) ncn_nx          */ 	0, 
/*( 75) ncn_yx          */ 	0, 
/*( 76) ncn_lx          */ 	0, 
/*( 77) nc_one_idx_n    */ 	0, 
/*( 78) nc_one_idx_y    */ 	0, 
/*( 79) nc_one_idx_l    */ 	0, 
/*( 80) nbu_e           */ 	0, 
/*( 81) nbu_n           */ 	0, 
/*( 82) nbu_y           */ 	0, 
/*( 83) nbu_l           */ 	0, 
/*( 84) nbu_one_n       */ 	0, 
/*( 85) nbu_one_y       */ 	0, 
/*( 86) nbu_one_l       */ 	0, 
/*( 87) nbn_p_n         */ 	0, 
/*( 88) nbn_p_y         */ 	0, 
/*( 89) nbn_p_l         */ 	0, 
/*( 90) nbn_n_n         */ 	0, 
/*( 91) nbn_n_y         */ 	0, 
/*( 92) nbn_n_l         */ 	0, 
/*( 93) con             */ 	0, 
/*( 94) xsp_rg          */ 	1, 
/*( 95) xsp_yeo         */ 	1, 
/*( 96) xsp_b           */ 	1, 
/*( 97) xsp_s           */ 	1, 
/*( 98) xsp_con_yeo     */ 	1, 
/*( 99) xsp_con_b       */ 	1, 
/*(100) xsp_con_s       */ 	1, 
/*(101) xsn_n           */ 	0, 
/*(102) xsn_y           */ 	0, 
/*(103) xsn_l           */ 	0, 
/*(104) xsn_ncp_spe_n   */ 	0, 
/*(105) xsn_ncp_n       */ 	0, 
/*(106) xsn_ncp_y       */ 	0, 
/*(107) xsn_ncp_l       */ 	0, 
/*(108) np_n            */ 	0, 
/*(109) np_y            */ 	0, 
/*(110) np_l            */ 	0, 
/*(111) np_nojub_n      */ 	0, 
/*(112) np_nojub_y      */ 	0, 
/*(113) np_nojub_l      */ 	0, 
/*(114) nno_n           */ 	0, 
/*(115) nno_y           */ 	0, 
/*(116) nno_l           */ 	0, 
/*(117) nnc_n           */ 	0, 
/*(118) nnc_y           */ 	0, 
/*(119) nnc_l           */ 	0, 
/*(120) mmn             */ 	0, 
/*(121) mma             */ 	0, 
/*(122) mmd             */ 	0, 
/*(123) ma_n            */ 	0, 
/*(124) ma_y            */ 	0, 
/*(125) ma_l            */ 	0, 
/*(126) j               */ 	0, 
/*(127) jp              */ 	0, 
/*(128) j_auto          */ 	0, 
/*(129) j_spe           */ 	0, 
/*(130) j_sub           */ 	0, 
/*(131) pv_rg           */ 	1, 
/*(132) pv_yeo          */ 	1, 
/*(133) pv_geo          */ 	1, 
/*(134) pv_neo          */ 	1, 
/*(135) pv_eu           */ 	1, 
/*(136) pv_reu          */ 	1, 
/*(137) pv_woo          */ 	1, 
/*(138) pv_reo          */ 	1, 
/*(139) pv_d            */ 	1, 
/*(140) pv_l            */ 	1, 
/*(141) pv_b            */ 	1, 
/*(142) pv_s            */ 	1, 
/*(143) pv_con_yeo      */ 	1, 
/*(144) pv_con_geo      */ 	1, 
/*(145) pv_con_neo      */ 	1, 
/*(146) pv_con_eu       */ 	1, 
/*(147) pv_con_reu      */ 	1, 
/*(148) pv_con_woo      */ 	1, 
/*(149) pv_con_reo      */ 	1, 
/*(150) pv_con_d        */ 	1, 
/*(151) pv_con_l        */ 	1, 
/*(152) pv_con_b        */ 	1, 
/*(153) pv_con_s        */ 	1, 
/*(154) pa_rg           */ 	1, 
/*(155) pa_iss          */ 	1, 
/*(156) pa_yeo          */ 	1, 
/*(157) pa_eu           */ 	1, 
/*(158) pa_reu          */ 	1, 
/*(159) pa_reo          */ 	1, 
/*(160) pa_l            */ 	1, 
/*(161) pa_b            */ 	1, 
/*(162) pa_s            */ 	1, 
/*(163) pa_h            */ 	1, 
/*(164) pa_con_yeo      */ 	1, 
/*(165) pa_con_eu       */ 	1, 
/*(166) pa_con_reu      */ 	1, 
/*(167) pa_con_reo      */ 	1, 
/*(168) pa_con_l        */ 	1, 
/*(169) pa_con_b        */ 	1, 
/*(170) pa_con_s        */ 	1, 
/*(171) pa_con_h        */ 	1, 
/*(172) pv_aux_rg       */ 	1, 
/*(173) pv_aux_yeo      */ 	1, 
/*(174) pv_aux_geo      */ 	1, 
/*(175) pv_aux_neo      */ 	1, 
/*(176) pv_aux_eu       */ 	1, 
/*(177) pv_aux_reu      */ 	1, 
/*(178) pv_aux_l        */ 	1, 
/*(179) pv_aux_b        */ 	1, 
/*(180) pv_aux_con_yeo  */ 	1, 
/*(181) pv_aux_con_geo  */ 	1, 
/*(182) pv_aux_con_neo  */ 	1, 
/*(183) pv_aux_con_eu   */ 	1, 
/*(184) pv_aux_con_reu  */ 	1, 
/*(185) pv_aux_con_l    */ 	1, 
/*(186) pv_aux_con_b    */ 	1, 
/*(187) pa_aux_rg       */ 	1, 
/*(188) pa_aux_iss      */ 	1, 
/*(189) pa_aux_yeo      */ 	1, 
/*(190) pa_aux_b        */ 	1, 
/*(191) pa_aux_con_yeo  */ 	1, 
/*(192) pa_aux_con_b    */ 	1, 
/*(193) nc_one_noidx_n  */ 	0, 
/*(194) nc_one_noidx_y  */ 	0, 
/*(195) nc_one_noidx_l  */ 	0, 
/*(196) xspv            */ 	0, 
/*(197) xspa            */ 	0, 
/*(198) ep              */ 	0, 
/*(199) ef              */ 	0, 
/*(200) ef_end          */ 	0, 
/*(201) ef_con          */ 	0, 
/*(202) efa             */ 	0, 
/*(203) etn             */ 	0, 
/*(204) ef_space        */ 	0, 
/*(205) xp_nq_per_idx   */ 	3, 
/*(206) xp_nq_per_noidx */ 	3, 
/*(207) xp_nq_loc_idx   */ 	3, 
/*(208) xp_nq_loc_noidx */ 	3, 
/*(209) xp_nq_etc_idx   */ 	3, 
/*(210) xp_nq_etc_noidx */ 	3, 
/*(211) xp_nc_idx       */ 	2, 
/*(212) xp_nc_noidx     */ 	3, 
/*(213) i               */ 	0, 
/*(214) boe             */ 	0, 
/*(215) eoe             */ 	0, 
/*(216) unknown         */ 	0, 
/*(217) unoun_n         */ 	0, 
/*(218) unoun_y         */ 	0, 
/*(219) unoun_l         */ 	0, 
/*(220) eng_n           */ 	0, 
/*(221) eng_y           */ 	0, 
/*(222) eng_c           */ 	0, 
/*(223) hanja           */ 	0, 
/*(224) mark            */ 	0};


/* *************************************************************  
             MorAn Ver 4.0의 대표태그명 헤더 

                                  By Kim, Eung Gyun 
                                  jchern@daumcorp.com 

   본 헤더는 대표태그명을 보관하는 헤더입니다.
   mkTagDef에 의해 자동으로 생성되었습니다.

   This Header is generated by mkTagDef at Tue Jun 27 12:43:00 2006
**************************************************************** */


static char     *L_MTag_Set[LEFT_TAG_CNT] = {
/*(  0) num_st          */ 	"num", 
/*(  1) num_ed          */ 	"num", 
/*(  2) num             */ 	"num", 
/*(  3) connum          */ 	"num", 
/*(  4) signnum         */ 	"num", 
/*(  5) alpabet         */ 	"eng", 
/*(  6) conalpabet      */ 	"eng", 
/*(  7) ascii           */ 	"asc", 
/*(  8) hanum           */ 	"num", 
/*(  9) ncp             */ 	"nc", 
/*( 10) ncn             */ 	"nc", 
/*( 11) nq_juso         */ 	"nq", 
/*( 12) nq_per          */ 	"nq", 
/*( 13) nq_per_his      */ 	"nq", 
/*( 14) nq_per_noc      */ 	"nq", 
/*( 15) nq_forper       */ 	"nq", 
/*( 16) nq_loc          */ 	"nq", 
/*( 17) nq_forloc       */ 	"nq", 
/*( 18) nq_hisloc       */ 	"nq", 
/*( 19) nq_com          */ 	"nq", 
/*( 20) nq_etc          */ 	"nq", 
/*( 21) nq_etc_noc      */ 	"nq", 
/*( 22) ncn_f           */ 	"nc", 
/*( 23) ncp_f           */ 	"nc", 
/*( 24) ncn_nocom       */ 	"nc", 
/*( 25) ncp_nocom       */ 	"nc", 
/*( 26) pv              */ 	"pv", 
/*( 27) pa              */ 	"pa", 
/*( 28) nq_per1         */ 	"nq", 
/*( 29) nq_per2         */ 	"nq", 
/*( 30) nbu             */ 	"nbu", 
/*( 31) nbu_one         */ 	"nbu", 
/*( 32) nbu_e           */ 	"nbu", 
/*( 33) nbn_p           */ 	"nbn", 
/*( 34) nbn_n           */ 	"nbn", 
/*( 35) nc_one_idx      */ 	"nc", 
/*( 36) pv_aux          */ 	"aux", 
/*( 37) pa_aux          */ 	"aux", 
/*( 38) xspv            */ 	"xs", 
/*( 39) xspa            */ 	"xs", 
/*( 40) xs_nbu          */ 	"xs", 
/*( 41) pa_iss          */ 	"pa", 
/*( 42) con             */ 	"con", 
/*( 43) xsp             */ 	"xsp", 
/*( 44) xsn_ncp         */ 	"xs", 
/*( 45) xsn_nq_per_idx  */ 	"nc", 
/*( 46) xsn_nq_per_noidx */ 	"xs", 
/*( 47) xsn_nq_per2_noidx */ 	"xs", 
/*( 48) xsn_nq_wrk_idx  */ 	"nc", 
/*( 49) xsn_nq_wrk_noidx */ 	"xs", 
/*( 50) xsn_nq_loc_idx  */ 	"nc", 
/*( 51) xsn_nq_loc_noidx */ 	"xs", 
/*( 52) xsn_nq_etc_idx  */ 	"nc", 
/*( 53) xsn_nq_etc_noidx */ 	"xs", 
/*( 54) xsn_nq_com_idx  */ 	"nc", 
/*( 55) xsn_nq_com_noidx */ 	"xs", 
/*( 56) xsn_nc_idx      */ 	"xs", 
/*( 57) xsn_nc_idx2     */ 	"xs", 
/*( 58) xsn_nc_noidx    */ 	"xs", 
/*( 59) np              */ 	"np", 
/*( 60) np_nojub        */ 	"np", 
/*( 61) nno             */ 	"nn", 
/*( 62) nnc             */ 	"nn", 
/*( 63) mmn             */ 	"mm", 
/*( 64) mma             */ 	"mm", 
/*( 65) mmd             */ 	"mm", 
/*( 66) ma              */ 	"ma", 
/*( 67) j_n             */ 	"j", 
/*( 68) j_yl            */ 	"j", 
/*( 69) j_nl            */ 	"j", 
/*( 70) j_y             */ 	"j", 
/*( 71) j_c             */ 	"j", 
/*( 72) j_per           */ 	"j", 
/*( 73) jp_y            */ 	"j", 
/*( 74) j_auto_n        */ 	"j", 
/*( 75) j_auto_yl       */ 	"j", 
/*( 76) j_auto_c        */ 	"j", 
/*( 77) jp_n            */ 	"j", 
/*( 78) j_spe_n         */ 	"j", 
/*( 79) j_spe_yl        */ 	"j", 
/*( 80) j_spe_nl        */ 	"j", 
/*( 81) j_spe_y         */ 	"j", 
/*( 82) j_spe_c         */ 	"j", 
/*( 83) j_spe_jp        */ 	"j", 
/*( 84) j_spe_idx       */ 	"j", 
/*( 85) j_sub_y         */ 	"j", 
/*( 86) j_sub_n         */ 	"j", 
/*( 87) j_sub_l         */ 	"j", 
/*( 88) nc_one_noidx    */ 	"1nc", 
/*( 89) xsnp            */ 	"xsp", 
/*( 90) ef              */ 	"e", 
/*( 91) ep              */ 	"e", 
/*( 92) etn             */ 	"e", 
/*( 93) xp              */ 	"xp", 
/*( 94) i               */ 	"i", 
/*( 95) boe             */ 	"boe", 
/*( 96) eoe             */ 	"eoe", 
/*( 97) unknown         */ 	"unknown", 
/*( 98) unoun           */ 	"user", 
/*( 99) eng             */ 	"eng", 
/*(100) numb            */ 	"numb", 
/*(101) hanja           */ 	"hanja", 
/*(102) mark            */ 	"mark"};



static char      *R_MTag_Set[RIGHT_TAG_CNT] = {
/*(  0) hanum_n         */ 	"num", 
/*(  1) hanum_y         */ 	"num", 
/*(  2) hanum_l         */ 	"num", 
/*(  3) hanum_x         */ 	"num", 
/*(  4) num_st          */ 	"num", 
/*(  5) num_ed          */ 	"num", 
/*(  6) num             */ 	"num", 
/*(  7) ascii           */ 	"num", 
/*(  8) alpabet         */ 	"num", 
/*(  9) conalpabet      */ 	"eng", 
/*( 10) connum          */ 	"num", 
/*( 11) signnum         */ 	"num", 
/*( 12) num_n           */ 	"num", 
/*( 13) num_y           */ 	"num", 
/*( 14) num_l           */ 	"num", 
/*( 15) num_x           */ 	"num", 
/*( 16) nq_per1         */ 	"nq", 
/*( 17) nq_juso_n       */ 	"nq", 
/*( 18) nq_juso_y       */ 	"nq", 
/*( 19) nq_juso_l       */ 	"nq", 
/*( 20) nq_per_n        */ 	"nq", 
/*( 21) nq_per_y        */ 	"nq", 
/*( 22) nq_per_l        */ 	"nq", 
/*( 23) nq_per_his_n    */ 	"nq", 
/*( 24) nq_per_his_y    */ 	"nq", 
/*( 25) nq_per_his_l    */ 	"nq", 
/*( 26) nq_per_noc_n    */ 	"nq", 
/*( 27) nq_per_noc_y    */ 	"nq", 
/*( 28) nq_per_noc_l    */ 	"nq", 
/*( 29) nq_forper_n     */ 	"nq", 
/*( 30) nq_forper_y     */ 	"nq", 
/*( 31) nq_forper_l     */ 	"nq", 
/*( 32) nq_per2_n       */ 	"nq", 
/*( 33) nq_per2_y       */ 	"nq", 
/*( 34) nq_per2_l       */ 	"nq", 
/*( 35) nq_loc_n        */ 	"nq", 
/*( 36) nq_loc_y        */ 	"nq", 
/*( 37) nq_loc_l        */ 	"nq", 
/*( 38) nq_forloc_n     */ 	"nq", 
/*( 39) nq_forloc_y     */ 	"nq", 
/*( 40) nq_forloc_l     */ 	"nq", 
/*( 41) nq_hisloc_n     */ 	"nq", 
/*( 42) nq_hisloc_y     */ 	"nq", 
/*( 43) nq_hisloc_l     */ 	"nq", 
/*( 44) nq_com_n        */ 	"nq", 
/*( 45) nq_com_y        */ 	"nq", 
/*( 46) nq_com_l        */ 	"nq", 
/*( 47) nq_etc_n        */ 	"nq", 
/*( 48) nq_etc_y        */ 	"nq", 
/*( 49) nq_etc_l        */ 	"nq", 
/*( 50) nq_etc_noc_n    */ 	"nq", 
/*( 51) nq_etc_noc_y    */ 	"nq", 
/*( 52) nq_etc_noc_l    */ 	"nq", 
/*( 53) ncp_y           */ 	"ncp", 
/*( 54) ncp_l           */ 	"ncp", 
/*( 55) ncp_n           */ 	"ncp", 
/*( 56) ncp_f_y         */ 	"ncp", 
/*( 57) ncp_f_l         */ 	"ncp", 
/*( 58) ncp_f_n         */ 	"ncp", 
/*( 59) ncp_nocom_n     */ 	"ncp", 
/*( 60) ncp_nocom_y     */ 	"ncp", 
/*( 61) ncp_nocom_l     */ 	"ncp", 
/*( 62) ncn_n           */ 	"ncn", 
/*( 63) ncn_y           */ 	"ncn", 
/*( 64) ncn_l           */ 	"ncn", 
/*( 65) ncn_f_n         */ 	"ncn", 
/*( 66) ncn_f_y         */ 	"ncn", 
/*( 67) ncn_f_l         */ 	"ncn", 
/*( 68) ncn_nocom_n     */ 	"ncp", 
/*( 69) ncn_nocom_y     */ 	"ncp", 
/*( 70) ncn_nocom_l     */ 	"ncp", 
/*( 71) ncp_nx          */ 	"ncp", 
/*( 72) ncp_yx          */ 	"ncp", 
/*( 73) ncp_lx          */ 	"ncp", 
/*( 74) ncn_nx          */ 	"ncn", 
/*( 75) ncn_yx          */ 	"ncn", 
/*( 76) ncn_lx          */ 	"ncn", 
/*( 77) nc_one_idx_n    */ 	"ncn", 
/*( 78) nc_one_idx_y    */ 	"ncn", 
/*( 79) nc_one_idx_l    */ 	"ncn", 
/*( 80) nbu_e           */ 	"nbu", 
/*( 81) nbu_n           */ 	"nbu", 
/*( 82) nbu_y           */ 	"nbu", 
/*( 83) nbu_l           */ 	"nbu", 
/*( 84) nbu_one_n       */ 	"nbu", 
/*( 85) nbu_one_y       */ 	"nbu", 
/*( 86) nbu_one_l       */ 	"nbu", 
/*( 87) nbn_p_n         */ 	"nbn", 
/*( 88) nbn_p_y         */ 	"nbn", 
/*( 89) nbn_p_l         */ 	"nbn", 
/*( 90) nbn_n_n         */ 	"nbn", 
/*( 91) nbn_n_y         */ 	"nbn", 
/*( 92) nbn_n_l         */ 	"nbn", 
/*( 93) con             */ 	"con", 
/*( 94) xsp_rg          */ 	"xsp", 
/*( 95) xsp_yeo         */ 	"xsp", 
/*( 96) xsp_b           */ 	"xsp", 
/*( 97) xsp_s           */ 	"xsp", 
/*( 98) xsp_con_yeo     */ 	"xsp", 
/*( 99) xsp_con_b       */ 	"xsp", 
/*(100) xsp_con_s       */ 	"xsp", 
/*(101) xsn_n           */ 	"xs", 
/*(102) xsn_y           */ 	"xs", 
/*(103) xsn_l           */ 	"xs", 
/*(104) xsn_ncp_spe_n   */ 	"xs", 
/*(105) xsn_ncp_n       */ 	"xs", 
/*(106) xsn_ncp_y       */ 	"xs", 
/*(107) xsn_ncp_l       */ 	"xs", 
/*(108) np_n            */ 	"np", 
/*(109) np_y            */ 	"np", 
/*(110) np_l            */ 	"np", 
/*(111) np_nojub_n      */ 	"np", 
/*(112) np_nojub_y      */ 	"np", 
/*(113) np_nojub_l      */ 	"np", 
/*(114) nno_n           */ 	"nn", 
/*(115) nno_y           */ 	"nn", 
/*(116) nno_l           */ 	"nn", 
/*(117) nnc_n           */ 	"nn", 
/*(118) nnc_y           */ 	"nn", 
/*(119) nnc_l           */ 	"nn", 
/*(120) mmn             */ 	"mm", 
/*(121) mma             */ 	"mm", 
/*(122) mmd             */ 	"mm", 
/*(123) ma_n            */ 	"ma", 
/*(124) ma_y            */ 	"ma", 
/*(125) ma_l            */ 	"ma", 
/*(126) j               */ 	"j", 
/*(127) jp              */ 	"j", 
/*(128) j_auto          */ 	"j", 
/*(129) j_spe           */ 	"j", 
/*(130) j_sub           */ 	"j", 
/*(131) pv_rg           */ 	"pv", 
/*(132) pv_yeo          */ 	"pv", 
/*(133) pv_geo          */ 	"pv", 
/*(134) pv_neo          */ 	"pv", 
/*(135) pv_eu           */ 	"pv", 
/*(136) pv_reu          */ 	"pv", 
/*(137) pv_woo          */ 	"pv", 
/*(138) pv_reo          */ 	"pv", 
/*(139) pv_d            */ 	"pv", 
/*(140) pv_l            */ 	"pv", 
/*(141) pv_b            */ 	"pv", 
/*(142) pv_s            */ 	"pv", 
/*(143) pv_con_yeo      */ 	"pv", 
/*(144) pv_con_geo      */ 	"pv", 
/*(145) pv_con_neo      */ 	"pv", 
/*(146) pv_con_eu       */ 	"pv", 
/*(147) pv_con_reu      */ 	"pv", 
/*(148) pv_con_woo      */ 	"pv", 
/*(149) pv_con_reo      */ 	"pv", 
/*(150) pv_con_d        */ 	"pv", 
/*(151) pv_con_l        */ 	"pv", 
/*(152) pv_con_b        */ 	"pv", 
/*(153) pv_con_s        */ 	"pv", 
/*(154) pa_rg           */ 	"pa", 
/*(155) pa_iss          */ 	"pa", 
/*(156) pa_yeo          */ 	"pa", 
/*(157) pa_eu           */ 	"pa", 
/*(158) pa_reu          */ 	"pa", 
/*(159) pa_reo          */ 	"pa", 
/*(160) pa_l            */ 	"pa", 
/*(161) pa_b            */ 	"pa", 
/*(162) pa_s            */ 	"pa", 
/*(163) pa_h            */ 	"pa", 
/*(164) pa_con_yeo      */ 	"pa", 
/*(165) pa_con_eu       */ 	"pa", 
/*(166) pa_con_reu      */ 	"pa", 
/*(167) pa_con_reo      */ 	"pa", 
/*(168) pa_con_l        */ 	"pa", 
/*(169) pa_con_b        */ 	"pa", 
/*(170) pa_con_s        */ 	"pa", 
/*(171) pa_con_h        */ 	"pa", 
/*(172) pv_aux_rg       */ 	"aux", 
/*(173) pv_aux_yeo      */ 	"aux", 
/*(174) pv_aux_geo      */ 	"aux", 
/*(175) pv_aux_neo      */ 	"aux", 
/*(176) pv_aux_eu       */ 	"aux", 
/*(177) pv_aux_reu      */ 	"aux", 
/*(178) pv_aux_l        */ 	"aux", 
/*(179) pv_aux_b        */ 	"aux", 
/*(180) pv_aux_con_yeo  */ 	"aux", 
/*(181) pv_aux_con_geo  */ 	"aux", 
/*(182) pv_aux_con_neo  */ 	"aux", 
/*(183) pv_aux_con_eu   */ 	"aux", 
/*(184) pv_aux_con_reu  */ 	"aux", 
/*(185) pv_aux_con_l    */ 	"aux", 
/*(186) pv_aux_con_b    */ 	"aux", 
/*(187) pa_aux_rg       */ 	"aux", 
/*(188) pa_aux_iss      */ 	"aux", 
/*(189) pa_aux_yeo      */ 	"aux", 
/*(190) pa_aux_b        */ 	"aux", 
/*(191) pa_aux_con_yeo  */ 	"aux", 
/*(192) pa_aux_con_b    */ 	"aux", 
/*(193) nc_one_noidx_n  */ 	"ncn", 
/*(194) nc_one_noidx_y  */ 	"ncn", 
/*(195) nc_one_noidx_l  */ 	"ncn", 
/*(196) xspv            */ 	"xs", 
/*(197) xspa            */ 	"xs", 
/*(198) ep              */ 	"e", 
/*(199) ef              */ 	"e", 
/*(200) ef_end          */ 	"e", 
/*(201) ef_con          */ 	"e", 
/*(202) efa             */ 	"e", 
/*(203) etn             */ 	"e", 
/*(204) ef_space        */ 	"e", 
/*(205) xp_nq_per_idx   */ 	"xp", 
/*(206) xp_nq_per_noidx */ 	"xp", 
/*(207) xp_nq_loc_idx   */ 	"xp", 
/*(208) xp_nq_loc_noidx */ 	"xp", 
/*(209) xp_nq_etc_idx   */ 	"xp", 
/*(210) xp_nq_etc_noidx */ 	"xp", 
/*(211) xp_nc_idx       */ 	"xp", 
/*(212) xp_nc_noidx     */ 	"xp", 
/*(213) i               */ 	"i", 
/*(214) boe             */ 	"boe", 
/*(215) eoe             */ 	"eoe", 
/*(216) unknown         */ 	"unknown", 
/*(217) unoun_n         */ 	"user", 
/*(218) unoun_y         */ 	"user", 
/*(219) unoun_l         */ 	"user", 
/*(220) eng_n           */ 	"eng", 
/*(221) eng_y           */ 	"eng", 
/*(222) eng_c           */ 	"eng", 
/*(223) hanja           */ 	"hanja", 
/*(224) mark            */ 	"mark"};


/* *************************************************************  
             MorAn Ver 4.0의 테그명 헤더 

                                  By Kim, Eung Gyun 
                                  jchern@daumcorp.com 

   본 헤더는 태그명을 보관하는 헤더입니다.
   mkTagDef에 의해 자동으로 생성되었습니다.

   This Header is generated by mkTagDef at Tue Jun 27 12:43:00 2006
**************************************************************** */


static char     *L_Tag_Set[LEFT_TAG_CNT] = {
/*(  0) num_st          */ 	"num_st", 
/*(  1) num_ed          */ 	"num_ed", 
/*(  2) num             */ 	"num", 
/*(  3) connum          */ 	"connum", 
/*(  4) signnum         */ 	"signnum", 
/*(  5) alpabet         */ 	"alpabet", 
/*(  6) conalpabet      */ 	"conalpabet", 
/*(  7) ascii           */ 	"ascii", 
/*(  8) hanum           */ 	"hanum", 
/*(  9) ncp             */ 	"ncp", 
/*( 10) ncn             */ 	"ncn", 
/*( 11) nq_juso         */ 	"nq_juso", 
/*( 12) nq_per          */ 	"nq_per", 
/*( 13) nq_per_his      */ 	"nq_per_his", 
/*( 14) nq_per_noc      */ 	"nq_per_noc", 
/*( 15) nq_forper       */ 	"nq_forper", 
/*( 16) nq_loc          */ 	"nq_loc", 
/*( 17) nq_forloc       */ 	"nq_forloc", 
/*( 18) nq_hisloc       */ 	"nq_hisloc", 
/*( 19) nq_com          */ 	"nq_com", 
/*( 20) nq_etc          */ 	"nq_etc", 
/*( 21) nq_etc_noc      */ 	"nq_etc_noc", 
/*( 22) ncn_f           */ 	"ncn_f", 
/*( 23) ncp_f           */ 	"ncp_f", 
/*( 24) ncn_nocom       */ 	"ncn_nocom", 
/*( 25) ncp_nocom       */ 	"ncp_nocom", 
/*( 26) pv              */ 	"pv", 
/*( 27) pa              */ 	"pa", 
/*( 28) nq_per1         */ 	"nq_per1", 
/*( 29) nq_per2         */ 	"nq_per2", 
/*( 30) nbu             */ 	"nbu", 
/*( 31) nbu_one         */ 	"nbu_one", 
/*( 32) nbu_e           */ 	"nbu_e", 
/*( 33) nbn_p           */ 	"nbn_p", 
/*( 34) nbn_n           */ 	"nbn_n", 
/*( 35) nc_one_idx      */ 	"nc_one_idx", 
/*( 36) pv_aux          */ 	"pv_aux", 
/*( 37) pa_aux          */ 	"pa_aux", 
/*( 38) xspv            */ 	"xspv", 
/*( 39) xspa            */ 	"xspa", 
/*( 40) xs_nbu          */ 	"xs_nbu", 
/*( 41) pa_iss          */ 	"pa_iss", 
/*( 42) con             */ 	"con", 
/*( 43) xsp             */ 	"xsp", 
/*( 44) xsn_ncp         */ 	"xsn_ncp", 
/*( 45) xsn_nq_per_idx  */ 	"xsn_nq_per_idx", 
/*( 46) xsn_nq_per_noidx */ 	"xsn_nq_per_noidx", 
/*( 47) xsn_nq_per2_noidx */ 	"xsn_nq_per2_noidx", 
/*( 48) xsn_nq_wrk_idx  */ 	"xsn_nq_wrk_idx", 
/*( 49) xsn_nq_wrk_noidx */ 	"xsn_nq_wrk_noidx", 
/*( 50) xsn_nq_loc_idx  */ 	"xsn_nq_loc_idx", 
/*( 51) xsn_nq_loc_noidx */ 	"xsn_nq_loc_noidx", 
/*( 52) xsn_nq_etc_idx  */ 	"xsn_nq_etc_idx", 
/*( 53) xsn_nq_etc_noidx */ 	"xsn_nq_etc_noidx", 
/*( 54) xsn_nq_com_idx  */ 	"xsn_nq_com_idx", 
/*( 55) xsn_nq_com_noidx */ 	"xsn_nq_com_noidx", 
/*( 56) xsn_nc_idx      */ 	"xsn_nc_idx", 
/*( 57) xsn_nc_idx2     */ 	"xsn_nc_idx2", 
/*( 58) xsn_nc_noidx    */ 	"xsn_nc_noidx", 
/*( 59) np              */ 	"np", 
/*( 60) np_nojub        */ 	"np_nojub", 
/*( 61) nno             */ 	"nno", 
/*( 62) nnc             */ 	"nnc", 
/*( 63) mmn             */ 	"mmn", 
/*( 64) mma             */ 	"mma", 
/*( 65) mmd             */ 	"mmd", 
/*( 66) ma              */ 	"ma", 
/*( 67) j_n             */ 	"j_n", 
/*( 68) j_yl            */ 	"j_yl", 
/*( 69) j_nl            */ 	"j_nl", 
/*( 70) j_y             */ 	"j_y", 
/*( 71) j_c             */ 	"j_c", 
/*( 72) j_per           */ 	"j_per", 
/*( 73) jp_y            */ 	"jp_y", 
/*( 74) j_auto_n        */ 	"j_auto_n", 
/*( 75) j_auto_yl       */ 	"j_auto_yl", 
/*( 76) j_auto_c        */ 	"j_auto_c", 
/*( 77) jp_n            */ 	"jp_n", 
/*( 78) j_spe_n         */ 	"j_spe_n", 
/*( 79) j_spe_yl        */ 	"j_spe_yl", 
/*( 80) j_spe_nl        */ 	"j_spe_nl", 
/*( 81) j_spe_y         */ 	"j_spe_y", 
/*( 82) j_spe_c         */ 	"j_spe_c", 
/*( 83) j_spe_jp        */ 	"j_spe_jp", 
/*( 84) j_spe_idx       */ 	"j_spe_idx", 
/*( 85) j_sub_y         */ 	"j_sub_y", 
/*( 86) j_sub_n         */ 	"j_sub_n", 
/*( 87) j_sub_l         */ 	"j_sub_l", 
/*( 88) nc_one_noidx    */ 	"nc_one_noidx", 
/*( 89) xsnp            */ 	"xsnp", 
/*( 90) ef              */ 	"ef", 
/*( 91) ep              */ 	"ep", 
/*( 92) etn             */ 	"etn", 
/*( 93) xp              */ 	"xp", 
/*( 94) i               */ 	"i", 
/*( 95) boe             */ 	"boe", 
/*( 96) eoe             */ 	"eoe", 
/*( 97) unknown         */ 	"unknown", 
/*( 98) unoun           */ 	"unoun", 
/*( 99) eng             */ 	"eng", 
/*(100) numb            */ 	"numb", 
/*(101) hanja           */ 	"hanja", 
/*(102) mark            */ 	"mark"};



static char      *R_Tag_Set[RIGHT_TAG_CNT] = {
/*(  0) hanum_n         */ 	"hanum_n", 
/*(  1) hanum_y         */ 	"hanum_y", 
/*(  2) hanum_l         */ 	"hanum_l", 
/*(  3) hanum_x         */ 	"hanum_x", 
/*(  4) num_st          */ 	"num_st", 
/*(  5) num_ed          */ 	"num_ed", 
/*(  6) num             */ 	"num", 
/*(  7) ascii           */ 	"ascii", 
/*(  8) alpabet         */ 	"alpabet", 
/*(  9) conalpabet      */ 	"conalpabet", 
/*( 10) connum          */ 	"connum", 
/*( 11) signnum         */ 	"signnum", 
/*( 12) num_n           */ 	"num_n", 
/*( 13) num_y           */ 	"num_y", 
/*( 14) num_l           */ 	"num_l", 
/*( 15) num_x           */ 	"num_x", 
/*( 16) nq_per1         */ 	"nq_per1", 
/*( 17) nq_juso_n       */ 	"nq_juso_n", 
/*( 18) nq_juso_y       */ 	"nq_juso_y", 
/*( 19) nq_juso_l       */ 	"nq_juso_l", 
/*( 20) nq_per_n        */ 	"nq_per_n", 
/*( 21) nq_per_y        */ 	"nq_per_y", 
/*( 22) nq_per_l        */ 	"nq_per_l", 
/*( 23) nq_per_his_n    */ 	"nq_per_his_n", 
/*( 24) nq_per_his_y    */ 	"nq_per_his_y", 
/*( 25) nq_per_his_l    */ 	"nq_per_his_l", 
/*( 26) nq_per_noc_n    */ 	"nq_per_noc_n", 
/*( 27) nq_per_noc_y    */ 	"nq_per_noc_y", 
/*( 28) nq_per_noc_l    */ 	"nq_per_noc_l", 
/*( 29) nq_forper_n     */ 	"nq_forper_n", 
/*( 30) nq_forper_y     */ 	"nq_forper_y", 
/*( 31) nq_forper_l     */ 	"nq_forper_l", 
/*( 32) nq_per2_n       */ 	"nq_per2_n", 
/*( 33) nq_per2_y       */ 	"nq_per2_y", 
/*( 34) nq_per2_l       */ 	"nq_per2_l", 
/*( 35) nq_loc_n        */ 	"nq_loc_n", 
/*( 36) nq_loc_y        */ 	"nq_loc_y", 
/*( 37) nq_loc_l        */ 	"nq_loc_l", 
/*( 38) nq_forloc_n     */ 	"nq_forloc_n", 
/*( 39) nq_forloc_y     */ 	"nq_forloc_y", 
/*( 40) nq_forloc_l     */ 	"nq_forloc_l", 
/*( 41) nq_hisloc_n     */ 	"nq_hisloc_n", 
/*( 42) nq_hisloc_y     */ 	"nq_hisloc_y", 
/*( 43) nq_hisloc_l     */ 	"nq_hisloc_l", 
/*( 44) nq_com_n        */ 	"nq_com_n", 
/*( 45) nq_com_y        */ 	"nq_com_y", 
/*( 46) nq_com_l        */ 	"nq_com_l", 
/*( 47) nq_etc_n        */ 	"nq_etc_n", 
/*( 48) nq_etc_y        */ 	"nq_etc_y", 
/*( 49) nq_etc_l        */ 	"nq_etc_l", 
/*( 50) nq_etc_noc_n    */ 	"nq_etc_noc_n", 
/*( 51) nq_etc_noc_y    */ 	"nq_etc_noc_y", 
/*( 52) nq_etc_noc_l    */ 	"nq_etc_noc_l", 
/*( 53) ncp_y           */ 	"ncp_y", 
/*( 54) ncp_l           */ 	"ncp_l", 
/*( 55) ncp_n           */ 	"ncp_n", 
/*( 56) ncp_f_y         */ 	"ncp_f_y", 
/*( 57) ncp_f_l         */ 	"ncp_f_l", 
/*( 58) ncp_f_n         */ 	"ncp_f_n", 
/*( 59) ncp_nocom_n     */ 	"ncp_nocom_n", 
/*( 60) ncp_nocom_y     */ 	"ncp_nocom_y", 
/*( 61) ncp_nocom_l     */ 	"ncp_nocom_l", 
/*( 62) ncn_n           */ 	"ncn_n", 
/*( 63) ncn_y           */ 	"ncn_y", 
/*( 64) ncn_l           */ 	"ncn_l", 
/*( 65) ncn_f_n         */ 	"ncn_f_n", 
/*( 66) ncn_f_y         */ 	"ncn_f_y", 
/*( 67) ncn_f_l         */ 	"ncn_f_l", 
/*( 68) ncn_nocom_n     */ 	"ncn_nocom_n", 
/*( 69) ncn_nocom_y     */ 	"ncn_nocom_y", 
/*( 70) ncn_nocom_l     */ 	"ncn_nocom_l", 
/*( 71) ncp_nx          */ 	"ncp_nx", 
/*( 72) ncp_yx          */ 	"ncp_yx", 
/*( 73) ncp_lx          */ 	"ncp_lx", 
/*( 74) ncn_nx          */ 	"ncn_nx", 
/*( 75) ncn_yx          */ 	"ncn_yx", 
/*( 76) ncn_lx          */ 	"ncn_lx", 
/*( 77) nc_one_idx_n    */ 	"nc_one_idx_n", 
/*( 78) nc_one_idx_y    */ 	"nc_one_idx_y", 
/*( 79) nc_one_idx_l    */ 	"nc_one_idx_l", 
/*( 80) nbu_e           */ 	"nbu_e", 
/*( 81) nbu_n           */ 	"nbu_n", 
/*( 82) nbu_y           */ 	"nbu_y", 
/*( 83) nbu_l           */ 	"nbu_l", 
/*( 84) nbu_one_n       */ 	"nbu_one_n", 
/*( 85) nbu_one_y       */ 	"nbu_one_y", 
/*( 86) nbu_one_l       */ 	"nbu_one_l", 
/*( 87) nbn_p_n         */ 	"nbn_p_n", 
/*( 88) nbn_p_y         */ 	"nbn_p_y", 
/*( 89) nbn_p_l         */ 	"nbn_p_l", 
/*( 90) nbn_n_n         */ 	"nbn_n_n", 
/*( 91) nbn_n_y         */ 	"nbn_n_y", 
/*( 92) nbn_n_l         */ 	"nbn_n_l", 
/*( 93) con             */ 	"con", 
/*( 94) xsp_rg          */ 	"xsp_rg", 
/*( 95) xsp_yeo         */ 	"xsp_yeo", 
/*( 96) xsp_b           */ 	"xsp_b", 
/*( 97) xsp_s           */ 	"xsp_s", 
/*( 98) xsp_con_yeo     */ 	"xsp_con_yeo", 
/*( 99) xsp_con_b       */ 	"xsp_con_b", 
/*(100) xsp_con_s       */ 	"xsp_con_s", 
/*(101) xsn_n           */ 	"xsn_n", 
/*(102) xsn_y           */ 	"xsn_y", 
/*(103) xsn_l           */ 	"xsn_l", 
/*(104) xsn_ncp_spe_n   */ 	"xsn_ncp_spe_n", 
/*(105) xsn_ncp_n       */ 	"xsn_ncp_n", 
/*(106) xsn_ncp_y       */ 	"xsn_ncp_y", 
/*(107) xsn_ncp_l       */ 	"xsn_ncp_l", 
/*(108) np_n            */ 	"np_n", 
/*(109) np_y            */ 	"np_y", 
/*(110) np_l            */ 	"np_l", 
/*(111) np_nojub_n      */ 	"np_nojub_n", 
/*(112) np_nojub_y      */ 	"np_nojub_y", 
/*(113) np_nojub_l      */ 	"np_nojub_l", 
/*(114) nno_n           */ 	"nno_n", 
/*(115) nno_y           */ 	"nno_y", 
/*(116) nno_l           */ 	"nno_l", 
/*(117) nnc_n           */ 	"nnc_n", 
/*(118) nnc_y           */ 	"nnc_y", 
/*(119) nnc_l           */ 	"nnc_l", 
/*(120) mmn             */ 	"mmn", 
/*(121) mma             */ 	"mma", 
/*(122) mmd             */ 	"mmd", 
/*(123) ma_n            */ 	"ma_n", 
/*(124) ma_y            */ 	"ma_y", 
/*(125) ma_l            */ 	"ma_l", 
/*(126) j               */ 	"j", 
/*(127) jp              */ 	"jp", 
/*(128) j_auto          */ 	"j_auto", 
/*(129) j_spe           */ 	"j_spe", 
/*(130) j_sub           */ 	"j_sub", 
/*(131) pv_rg           */ 	"pv_rg", 
/*(132) pv_yeo          */ 	"pv_yeo", 
/*(133) pv_geo          */ 	"pv_geo", 
/*(134) pv_neo          */ 	"pv_neo", 
/*(135) pv_eu           */ 	"pv_eu", 
/*(136) pv_reu          */ 	"pv_reu", 
/*(137) pv_woo          */ 	"pv_woo", 
/*(138) pv_reo          */ 	"pv_reo", 
/*(139) pv_d            */ 	"pv_d", 
/*(140) pv_l            */ 	"pv_l", 
/*(141) pv_b            */ 	"pv_b", 
/*(142) pv_s            */ 	"pv_s", 
/*(143) pv_con_yeo      */ 	"pv_con_yeo", 
/*(144) pv_con_geo      */ 	"pv_con_geo", 
/*(145) pv_con_neo      */ 	"pv_con_neo", 
/*(146) pv_con_eu       */ 	"pv_con_eu", 
/*(147) pv_con_reu      */ 	"pv_con_reu", 
/*(148) pv_con_woo      */ 	"pv_con_woo", 
/*(149) pv_con_reo      */ 	"pv_con_reo", 
/*(150) pv_con_d        */ 	"pv_con_d", 
/*(151) pv_con_l        */ 	"pv_con_l", 
/*(152) pv_con_b        */ 	"pv_con_b", 
/*(153) pv_con_s        */ 	"pv_con_s", 
/*(154) pa_rg           */ 	"pa_rg", 
/*(155) pa_iss          */ 	"pa_iss", 
/*(156) pa_yeo          */ 	"pa_yeo", 
/*(157) pa_eu           */ 	"pa_eu", 
/*(158) pa_reu          */ 	"pa_reu", 
/*(159) pa_reo          */ 	"pa_reo", 
/*(160) pa_l            */ 	"pa_l", 
/*(161) pa_b            */ 	"pa_b", 
/*(162) pa_s            */ 	"pa_s", 
/*(163) pa_h            */ 	"pa_h", 
/*(164) pa_con_yeo      */ 	"pa_con_yeo", 
/*(165) pa_con_eu       */ 	"pa_con_eu", 
/*(166) pa_con_reu      */ 	"pa_con_reu", 
/*(167) pa_con_reo      */ 	"pa_con_reo", 
/*(168) pa_con_l        */ 	"pa_con_l", 
/*(169) pa_con_b        */ 	"pa_con_b", 
/*(170) pa_con_s        */ 	"pa_con_s", 
/*(171) pa_con_h        */ 	"pa_con_h", 
/*(172) pv_aux_rg       */ 	"pv_aux_rg", 
/*(173) pv_aux_yeo      */ 	"pv_aux_yeo", 
/*(174) pv_aux_geo      */ 	"pv_aux_geo", 
/*(175) pv_aux_neo      */ 	"pv_aux_neo", 
/*(176) pv_aux_eu       */ 	"pv_aux_eu", 
/*(177) pv_aux_reu      */ 	"pv_aux_reu", 
/*(178) pv_aux_l        */ 	"pv_aux_l", 
/*(179) pv_aux_b        */ 	"pv_aux_b", 
/*(180) pv_aux_con_yeo  */ 	"pv_aux_con_yeo", 
/*(181) pv_aux_con_geo  */ 	"pv_aux_con_geo", 
/*(182) pv_aux_con_neo  */ 	"pv_aux_con_neo", 
/*(183) pv_aux_con_eu   */ 	"pv_aux_con_eu", 
/*(184) pv_aux_con_reu  */ 	"pv_aux_con_reu", 
/*(185) pv_aux_con_l    */ 	"pv_aux_con_l", 
/*(186) pv_aux_con_b    */ 	"pv_aux_con_b", 
/*(187) pa_aux_rg       */ 	"pa_aux_rg", 
/*(188) pa_aux_iss      */ 	"pa_aux_iss", 
/*(189) pa_aux_yeo      */ 	"pa_aux_yeo", 
/*(190) pa_aux_b        */ 	"pa_aux_b", 
/*(191) pa_aux_con_yeo  */ 	"pa_aux_con_yeo", 
/*(192) pa_aux_con_b    */ 	"pa_aux_con_b", 
/*(193) nc_one_noidx_n  */ 	"nc_one_noidx_n", 
/*(194) nc_one_noidx_y  */ 	"nc_one_noidx_y", 
/*(195) nc_one_noidx_l  */ 	"nc_one_noidx_l", 
/*(196) xspv            */ 	"xspv", 
/*(197) xspa            */ 	"xspa", 
/*(198) ep              */ 	"ep", 
/*(199) ef              */ 	"ef", 
/*(200) ef_end          */ 	"ef_end", 
/*(201) ef_con          */ 	"ef_con", 
/*(202) efa             */ 	"efa", 
/*(203) etn             */ 	"etn", 
/*(204) ef_space        */ 	"ef_space", 
/*(205) xp_nq_per_idx   */ 	"xp_nq_per_idx", 
/*(206) xp_nq_per_noidx */ 	"xp_nq_per_noidx", 
/*(207) xp_nq_loc_idx   */ 	"xp_nq_loc_idx", 
/*(208) xp_nq_loc_noidx */ 	"xp_nq_loc_noidx", 
/*(209) xp_nq_etc_idx   */ 	"xp_nq_etc_idx", 
/*(210) xp_nq_etc_noidx */ 	"xp_nq_etc_noidx", 
/*(211) xp_nc_idx       */ 	"xp_nc_idx", 
/*(212) xp_nc_noidx     */ 	"xp_nc_noidx", 
/*(213) i               */ 	"i", 
/*(214) boe             */ 	"boe", 
/*(215) eoe             */ 	"eoe", 
/*(216) unknown         */ 	"unknown", 
/*(217) unoun_n         */ 	"unoun_n", 
/*(218) unoun_y         */ 	"unoun_y", 
/*(219) unoun_l         */ 	"unoun_l", 
/*(220) eng_n           */ 	"eng_n", 
/*(221) eng_y           */ 	"eng_y", 
/*(222) eng_c           */ 	"eng_c", 
/*(223) hanja           */ 	"hanja", 
/*(224) mark            */ 	"mark"};


/* *************************************************************  
             MorAn Ver 4.0의 끝 헤더 

                                  By Kim, Eung Gyun 
                                  jchern@daumcorp.com 

   본 헤더는 끝입니다.
   mkTagDef에 의해 자동으로 생성되었습니다.

   This Header is generated by mkTagDef at Tue Jun 27 12:43:00 2006
**************************************************************** */



#endif
