/* $Id$ */
#ifndef _HTTP_STATUS_FLAG_H_
#define _HTTP_STATUS_FLAG_H_

#define CON_FLAG_CONNECTED		0x01
#define CON_FLAG_CONNECTING		0x02
#define CON_FLAG_REQUEST_OK		0x04
#define CON_FLAG_RESPONSE_OK	0x08
#define CON_FLAG_CONNECTFAILED 	0x10
#define CON_FLAG_REQUESTFAILED 	0x40
#define CON_FLAG_RESPONSEFAILED 0x80
#define CON_FLAG_CLEAN 0x00

#endif //_HTTP_STATUS_FLAG_H_
