#!/bin/sh
# $Id$ 
#
# buildconf: Build the autoconfiguration files.

set -x

trap 'rm -f aclocal.m4 ; exit 0' 1 2 3 13 15

while test $# -gt 0
do
  # Normalize
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

#   case "$1" in
#   --with-apr=*)
#   apr_src_dir=$optarg
#   ;;
#   esac

  shift
done

###############################################################################
aclocal -I build

#rm -f libtool
#ln -s configure.ac configure.in
libtoolize --automake --force --copy
#rm -f configure.in

autoheader
automake --add-missing --copy --force
autoconf

exit 0

