#!/bin/sh
# $Id$ 
#
# buildconf: Build the autoconfiguration files.

#set -x

trap 'rm -f aclocal.m4 ; exit 0' 0 1 2 3 13 15

while test $# -gt 0
do
  # Normalize
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

#   case "$1" in
#   --with-apr=*)
#   apr_src_dir=$optarg
#   ;;
#   esac

  shift
done


###############################################################################
echo building ${SB_VERSION_STRING}

#rm -f aclocal.m4
echo running aclocal -I build ...
aclocal -I build

echo running libtoolize --automake --force --copy ...
#rm -f libtool
ln -s configure.ac configure.in
libtoolize --automake --force --copy
rm -f configure.in

echo running autoheader ...
#rm -f include/auto_config.h.in
autoheader
#  chmod 444 include/auto_config.h.in

echo running automake --foreign --add-missing --copy --force ...
automake --foreign --add-missing --copy --force

echo running autoconf to build configure
#rm -f configure
autoconf

exit 0

