#!/bin/sh
# $Id$ 

set -x
dir=`pwd`
reldir=`basename $dir`
if [ "$reldir" = "nextsoftbot" ]
then
	ctags -R --exclude=Makefile server client modules include platform
	#ctags-exuberant -R
	echo "set tags="$dir"/tags" >> .vimrc
	find . -type d | egrep -v --regex="CVS|\.libs|\.deps" | egrep --regex="include|server|modules|platform|srclib|client" | awk '{ print "cp .vimrc " $1"/" }' | sh
else
	echo "you must run this script in project root directory"
fi
