#!/usr/bin/perl -w

use lib "../lib/perl";
use lib "./lib/perl";
use strict;
use Getopt::Std;
use SoftWise::SoftBot;

sub BEGIN {
	$Getopt::Std::STANDARD_HELP_VERSION = 1;
	our $VERSION = "1.0";
}

sub HELP_MESSAGE {
	print <<END;
Usage: $0 [-s]  < file
    file     - document list file, output of `search' command.

Options:
    -s       - silent mode  

Required Environemnt Variables:
    SB_HOST  - hostname of search server
    SB_PORT  - port number that softbot use
END
	exit;
}

###################################
#         options Á¤¸®

my ( $silent_output );

HELP_MESSAGE() unless( getopts( "s" ) );
our ( $opt_s );

$silent_output = $opt_s;

my $host = $ENV{SB_HOST};
my $port = $ENV{SB_PORT};

HELP_MESSAGE() unless ($host and $port);

while ( <STDIN> ) {
  /^\s*#/ and do {
    print $_ unless $silent_output;
    next;
  };

  /DID=(\d+)/ and do {
    my $did = $1;
    my $sb = new SoftWise::SoftBot($host, $port) or die "cannot connect to softbot: $!\n";
    my $ret = $sb->delete_doc($did);
    if ($ret) { print "deleted DID=$1\n"; }
    else { print "failed to delete DID=$1\n"; }
  };
}

exit;

