#!/usr/bin/perl -w
# $Id$
use strict;

use Benchmark qw(:hireswallclock);
use LWP::UserAgent;
use HTTP::Request::Common;

my $host  = shift;
my $port  = shift;
my $file = shift;
my $confirm = shift || 0;
my $stop = 0;
my $max_size = 10_000_000;

unless ($host and $port and $header and $file) {
	print <<END;
Usage: $0 <host> <port> <header> <file> [<confirm>]
    host
    port
    header  - fieldname#fieldnum:morp_id^ ex) body#0:11^ 
    file    - text data file or cdm data file to register
    confirm - set 1 if you want to confirm every document by key input
END
	exit;
}

process_data_file($host, $port, $header, $file, $confirm);
exit;


sub process_data_file {
	my $host  = shift;
	my $port  = shift;
    my $header = shift;
	my $file = shift;
	my $confirm = shift;

	open(FILE, $file) or die "cannot open file: $!";

	my $state = 0;
	my ($dit, $body, $count) = ("", "", 0);
	while (<FILE>) {
		last if $stop;

		if ($state == 0) {
			/TextForTest/ and do {
				print "Regular Data File\n";
				next;
			};
			/^-{78,82}$/ and do {
				$state = 1;
				next;
			};
			/OID=/ and do {
				$dit = $_;
				chomp $dit;
				$body = "";
				$state = 2;
				print "Irregular Data File! Anyway I will handle this.\n";
				next;
			};
		}
		if ($state == 1) {
			# 구분선이 연속으로 오는 경우도 그냥 처리
			/^-{78,82}$/ and do {
				$state = 1;
				next;
			};

			$dit = $_;
			chomp $dit;
			$body = "";
			$state = 2;
		}

		if ($state == 2) {
			$state = 3; # empty line
			next;
		}

		if ($state == 3) {
			/^-{78,82}$/ and $body =~ /<\/Document>/ and do {
				$state = 1;
				print "." if (($count % 50) == 0);
				if ($confirm > 1 and $count < $confirm) {
					$count++;
					next;
				}
				morph_analyze($dit, $body, $host, $port, $header);
				$count++;
				next;
			};
			$body .= $_;
		}
	}
	close(FILE);
	print "\nregistered $count docs.\n";
}


sub morph_analyze
{
  print STDERR ".";
  return;

}





__END__





my $ua = LWP::UserAgent->new;
$ua->agent("WiseBot Client/0.1");



  my $escaped_query = escape($query);
  my $t1 = new Benchmark;
  my $r = $ua->request(GET $target . "?q=" . $escaped_query);
  my $t2 = new Benchmark;
  my $output;
  if ($r->is_success)
  {
    $output = $r->content;
    $output =~ s/(<\?xml [^>]*\?>)/$1\n<?xml-stylesheet type="text\/xsl" href="$xslt"?>/i if $xslt;

    #$output = $r->as_string;
  } else {
    $output = $r->error_as_HTML;
  }
  my $elapsed_time = "<loading_time>" . timestr(timediff($t2,$t1), 'nop') . "</loading_time>";
  $output =~ s/(<xml[^>]*>|<html[^>]*>)/$1 $elapsed_time/i;
  my $content_type = "text/plain";
  $content_type = "text/xml"  if (substr($output,0,150) =~ m/<xml/i);
  $content_type = "text/html" if (substr($output,0,150) =~ m/<html/i);

  print $q->header(-type=>$content_type, -charset=>'cp949');
  print <<END;
$output
END
  exit;
} else {

print $q->header(-type=>"text/html", -charset=>'cp949', -expires => '-1y');
print <<END;
<html>
<head>
<title>WiseBot Search Debug</title>
<style type="text/css"><!--
BODY {
 font-family : Helvetica, sans-serif;
 font-size   : 10pt;
}

DIV  {
 margin: 3px;
}


* { outline: 1px dotted red; padding: 1px}
* * { outline: 1px dotted green; padding: 3px }
* * * { outline: 1px dotted orange; padding: 3px }
* * * * { outline: 1px dotted blue; padding: 3px }
/* FIXME uncomment when you debug.
* * * * * { outline: 2px solid red; padding: 3px }
* * * * * * { outline: 2px solid green }
* * * * * * * { outline: 2px solid orange }
* * * * * * * * { outline: 2px solid blue }
*/

--></style>
</head>
<body>
<h3>WiseBot Search Debug <small>($cvs_id)</small></h3>

<form id="search" action="#" style="float:left" target="result" method="post">
<div style="float:left;"> <input type="text" name="target" size="50" value="$target"/> </div> <br style="clear:left">
<div style="float:left;"> <textarea name="query" rows="10" cols="50">$query</textarea> </div> <br style="clear:left">
<div style="float:left"> 
  <select name="xslt" style="width:10em">
  <option value="">no xsl</option>
  <option value="search.xsl">search.xsl</option>
  <option value="search.xsl">search.xsl</option>
  <option value="search.xsl">search.xsl</option>
  </select>
</div>
<div style="float:left"> <input type="submit" value=" Search "/> </div>
<input type="hidden" name="submit" value="ok"/>
</form>

<div style="float:right;">
<textarea name="example" rows="15" cols="50">
----------------------------------------------
본문검색
----------------------------------------------
SELECT *
SEARCH body:거울
ORDER_BY RELEVANCY DESC
LIMIT 0, 10

----------------------------------------------
통합검색
----------------------------------------------
SELECT *
SEARCH body:거울
VIRTUAL_ID BOOKID
(
GROUP_BY BOOKID LIMIT 3
ORDER_BY RELEVANCY DESC
)
ORDER_BY RELEVANCY DESC
LIMIT 2

--------------
SELECT *
SEARCH pattern:softwisezzz
VIRTUAL_ID BOOKID
(
WHERE bookid=2307
GROUP_BY BOOKID LIMIT 2, 5
ORDER_BY RELEVANCY DESC, page
)
OUTPUT_STYLE SOFTBOT4
</textarea>
</div>



<br style="clear:left">
<iframe name="result" width="100%" height="100%"> </iframe>
</body>
END

print q( <address> $Id$ </address> </html> );

}
