/* include/auto_config.h.  Generated by configure.  */
/* include/auto_config.h.in.  Generated from configure.ac by autoheader.  */

#ifndef AUTO_CONFIG_H
#define AUTO_CONFIG_H 1

#include "auto_defines.h"

#define DEFAULT_CONFIG_FILE     "etc/softbot.conf"
#define DEFAULT_ERROR_LOG_FILE  "logs/error_log"
#define DEFAULT_QUERY_LOG_FILE  "logs/query_log"
#define DEFAULT_PID_FILE        "logs/softbotd.pid"
#define DEFAULT_REGISTRY_FILE   "dat/softbotd.reg"

#define CONFIG_PATH     "etc"
#define DB_PATH         "dat"
#define LOG_PATH        "logs"




/* checking system environment */
/* #undef LINUX */
#define CYGWIN 1
/* #undef FREEBSD */
/* #undef SOLARIS */
/* #undef AIX5 */

/* whether indexer saves forward index or not. default is NOT using it. */
#define FORWARD_INDEX 0

/* whether to use apr, apr-util or not. default is NOT using it. */
/* do not use APR anymore. 2004/08/03 */
/* #define USE_APR 0 */

/* hit size of hits of doc_hit_t. default size is 4 */
#define HIT_SIZE 4

/* If you don't have setproctitle, SB_ARGV_TYPE needs to be set to either
* SB_ARGV_NEW (replace argv[] arguments), SB_ARGV_WRITEABLE (overwrite
* argv[]), SB_ARGV_PSTAT (use the pstat function), or SB_ARGV_PSSTRINGS
* (use PS_STRINGS).
*
* configure should, we hope <wink>, detect this for you.
*/

#define SB_ARGV_NONE        0
#define SB_ARGV_NEW         1
#define SB_ARGV_WRITEABLE   2
#define SB_ARGV_PSTAT       3
#define SB_ARGV_PSSTRINGS   4

#define SB_ARGV_TYPE SB_ARGV_WRITABLE



/* see if the compiler supports __attribute__ gracefully */
#define ATTR_UNUSED __attribute__((__unused__))

/* Define to 1 if you have the `alloca' function. */
/* #undef HAVE_ALLOCA */

/* Define to 1 if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `getaddrinfo' function. */
/* #undef HAVE_GETADDRINFO */

/* Define to 1 if you have the `getenv' function. */
#define HAVE_GETENV 1

/* Define to 1 if you have the `getopt' function. */
#define HAVE_GETOPT 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the `getopt_long' function. */
#define HAVE_GETOPT_LONG 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <io.h> header file. */
#define HAVE_IO_H 1

/* Define to 1 if you have the `madvise' function. */
/* #undef HAVE_MADVISE */

/* Define to 1 if you have the `memalign' function. */
#define HAVE_MEMALIGN 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mergesort' function. */
/* #undef HAVE_MERGESORT */

/* Define to 1 if you have the `mmap' function. */
#define HAVE_MMAP 1

/* Define to 1 if you have the `pstat' function. */
/* #undef HAVE_PSTAT */

/* Define to 1 if you have the `setproctitle' function. */
/* #undef HAVE_SETPROCTITLE */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/mman.h> header file. */
#define HAVE_SYS_MMAN_H 1

/* Define to 1 if you have the <sys/pstat.h> header file. */
/* #undef HAVE_SYS_PSTAT_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/times.h> header file. */
#define HAVE_SYS_TIMES_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `valloc' function. */
#define HAVE_VALLOC 1

/* whether __progname and __progname__full are available */
/* #undef HAVE___PROGNAME */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "support@softwise.co.kr"

/* Define to the full name of this package. */
#define PACKAGE_NAME "SoftBot"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "SoftBot 6.0.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "softbot-6.0.0"

/* Define to the version of this package. */
#define PACKAGE_VERSION "6.0.0"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
#define YYTEXT_POINTER 1


#endif /* AUTO_CONFIG_H */

